// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_CustomerWithCustomer.To_CustAddrDepdntInformation
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSelectQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Customer")]
        #pragma warning disable CS1591
        Customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressID")]
        #pragma warning disable CS1591
        AddressID,
        #pragma warning restore CS1591
        [EnumMember(Value = "ExpressTrainStationName")]
        #pragma warning disable CS1591
        ExpressTrainStationName,
        #pragma warning restore CS1591
        [EnumMember(Value = "TrainStationName")]
        #pragma warning disable CS1591
        TrainStationName,
        #pragma warning restore CS1591
        [EnumMember(Value = "CityCode")]
        #pragma warning disable CS1591
        CityCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "County")]
        #pragma warning disable CS1591
        County,
        #pragma warning restore CS1591
    }
}
