// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_BPFinancialServicesExtnWithBusinessPartner
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSelectQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BusinessPartner")]
        #pragma warning disable CS1591
        BusinessPartner,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerIsVIP")]
        #pragma warning disable CS1591
        BusinessPartnerIsVIP,
        #pragma warning restore CS1591
        [EnumMember(Value = "TradingPartner")]
        #pragma warning disable CS1591
        TradingPartner,
        #pragma warning restore CS1591
        [EnumMember(Value = "FactoryCalendar")]
        #pragma warning disable CS1591
        FactoryCalendar,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerOfficeCountry")]
        #pragma warning disable CS1591
        BusinessPartnerOfficeCountry,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerOfficeRegion")]
        #pragma warning disable CS1591
        BusinessPartnerOfficeRegion,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPRegisteredOfficeName")]
        #pragma warning disable CS1591
        BPRegisteredOfficeName,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPBalanceSheetCurrency")]
        #pragma warning disable CS1591
        BPBalanceSheetCurrency,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPLastCptlIncrAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPLastCptlIncrAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPLastCapitalIncreaseYear")]
        #pragma warning disable CS1591
        BPLastCapitalIncreaseYear,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPBalanceSheetDisplayType")]
        #pragma warning disable CS1591
        BPBalanceSheetDisplayType,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerCitizenship")]
        #pragma warning disable CS1591
        BusinessPartnerCitizenship,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPMaritalPropertyRegime")]
        #pragma warning disable CS1591
        BPMaritalPropertyRegime,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerIncomeCurrency")]
        #pragma warning disable CS1591
        BusinessPartnerIncomeCurrency,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPNumberOfChildren")]
        #pragma warning disable CS1591
        BPNumberOfChildren,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPNumberOfHouseholdMembers")]
        #pragma warning disable CS1591
        BPNumberOfHouseholdMembers,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPAnnualNetIncAmtInIncomeCrcy")]
        #pragma warning disable CS1591
        BPAnnualNetIncAmtInIncomeCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPMonthlyNetIncAmtInIncomeCrcy")]
        #pragma warning disable CS1591
        BPMonthlyNetIncAmtInIncomeCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPAnnualNetIncomeYear")]
        #pragma warning disable CS1591
        BPAnnualNetIncomeYear,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPMonthlyNetIncomeMonth")]
        #pragma warning disable CS1591
        BPMonthlyNetIncomeMonth,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPMonthlyNetIncomeYear")]
        #pragma warning disable CS1591
        BPMonthlyNetIncomeYear,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPPlaceOfDeathName")]
        #pragma warning disable CS1591
        BPPlaceOfDeathName,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerIsUnwanted")]
        #pragma warning disable CS1591
        CustomerIsUnwanted,
        #pragma warning restore CS1591
        [EnumMember(Value = "UndesirabilityReason")]
        #pragma warning disable CS1591
        UndesirabilityReason,
        #pragma warning restore CS1591
        [EnumMember(Value = "UndesirabilityComment")]
        #pragma warning disable CS1591
        UndesirabilityComment,
        #pragma warning restore CS1591
        [EnumMember(Value = "LastCustomerContactDate")]
        #pragma warning disable CS1591
        LastCustomerContactDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPGroupingCharacter")]
        #pragma warning disable CS1591
        BPGroupingCharacter,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPLetterSalutation")]
        #pragma warning disable CS1591
        BPLetterSalutation,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerTargetGroup")]
        #pragma warning disable CS1591
        BusinessPartnerTargetGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerEmployeeGroup")]
        #pragma warning disable CS1591
        BusinessPartnerEmployeeGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerIsEmployee")]
        #pragma warning disable CS1591
        BusinessPartnerIsEmployee,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTermnBusRelationsBankDate")]
        #pragma warning disable CS1591
        BPTermnBusRelationsBankDate,
        #pragma warning restore CS1591
    }
}
