// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using S4HANABusinessPartners.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID
{
    /// <summary>
    /// Builds and executes requests for operations under \A_CustomerSalesAreaText(Customer=&apos;{Customer}&apos;,SalesOrganization=&apos;{SalesOrganization}&apos;,DistributionChannel=&apos;{DistributionChannel}&apos;,Division=&apos;{Division}&apos;,Language=&apos;{Language}&apos;,LongTextID=&apos;{LongTextID}&apos;)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="customer">Customer Number</param>
        /// <param name="distributionChannel">Distribution Channel</param>
        /// <param name="division">Division</param>
        /// <param name="language">Language key</param>
        /// <param name="longTextID">Text ID</param>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        /// <param name="salesOrganization">Sales Organization</param>
        public A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter, string customer = "", string distributionChannel = "", string division = "", string language = "", string longTextID = "", string salesOrganization = "") : base(requestAdapter, "{+baseurl}/A_CustomerSalesAreaText(Customer='{Customer}',SalesOrganization='{SalesOrganization}',DistributionChannel='{DistributionChannel}',Division='{Division}',Language='{Language}',LongTextID='{LongTextID}'){?%24select}", pathParameters)
        {
            if (!string.IsNullOrWhiteSpace(customer)) PathParameters.Add("Customer", customer);
            if (!string.IsNullOrWhiteSpace(distributionChannel)) PathParameters.Add("DistributionChannel", distributionChannel);
            if (!string.IsNullOrWhiteSpace(division)) PathParameters.Add("Division", division);
            if (!string.IsNullOrWhiteSpace(language)) PathParameters.Add("Language", language);
            if (!string.IsNullOrWhiteSpace(longTextID)) PathParameters.Add("LongTextID", longTextID);
            if (!string.IsNullOrWhiteSpace(salesOrganization)) PathParameters.Add("SalesOrganization", salesOrganization);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/A_CustomerSalesAreaText(Customer='{Customer}',SalesOrganization='{SalesOrganization}',DistributionChannel='{DistributionChannel}',Division='{Division}',Language='{Language}',LongTextID='{LongTextID}'){?%24select}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes customer sales area text data identified by Customer, SalesOrganization, DistributionChannel, Division, and Language.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retreives customer sales area text data by Customer, SalesOrganization, DistributionChannel, Division, and Language.
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDGetResponse?> GetAsA_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDGetResponseAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilder.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDGetResponse> GetAsA_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDGetResponseAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilder.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDGetResponse>(requestInfo, global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retreives customer sales area text data by Customer, SalesOrganization, DistributionChannel, Division, and Language.
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
        [Obsolete("This method is obsolete. Use GetAsA_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDResponse?> GetAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilder.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDResponse> GetAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilder.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDResponse>(requestInfo, global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates customer sales area text data identified by Customer, SalesOrganization, DistributionChannel, Division and Language
        /// </summary>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PatchAsync(global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PatchAsync(global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes customer sales area text data identified by Customer, SalesOrganization, DistributionChannel, Division, and Language.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retreives customer sales area text data by Customer, SalesOrganization, DistributionChannel, Division, and Language.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilder.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilder.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates customer sales area text data identified by Customer, SalesOrganization, DistributionChannel, Division and Language
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilder WithUrl(string rawUrl)
        {
            return new global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Retreives customer sales area text data by Customer, SalesOrganization, DistributionChannel, Division, and Language.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilderGetQueryParameters 
        {
            /// <summary>Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=68)</summary>
            [Obsolete("This property is deprecated, use SelectAsGetSelectQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24select")]
            public string[]? Select { get; set; }
#nullable restore
#else
            [QueryParameter("%24select")]
            public string[] Select { get; set; }
#endif
            /// <summary>Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=68)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24select")]
            public global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.GetSelectQueryParameterType[]? SelectAsGetSelectQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("%24select")]
            public global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.GetSelectQueryParameterType[] SelectAsGetSelectQueryParameterType { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilderGetRequestConfiguration : RequestConfiguration<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextID.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilder.A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_CustomerSalesAreaTextWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithLanguageWithLongTextIDRequestBuilderPatchRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
