// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_BPContactPersonWbsteURL
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrderbyQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "RelationshipNumber")]
        #pragma warning disable CS1591
        RelationshipNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "RelationshipNumber desc")]
        #pragma warning disable CS1591
        RelationshipNumberDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerCompany")]
        #pragma warning disable CS1591
        BusinessPartnerCompany,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerCompany desc")]
        #pragma warning disable CS1591
        BusinessPartnerCompanyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerPerson")]
        #pragma warning disable CS1591
        BusinessPartnerPerson,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerPerson desc")]
        #pragma warning disable CS1591
        BusinessPartnerPersonDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "ValidityEndDate")]
        #pragma warning disable CS1591
        ValidityEndDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "ValidityEndDate desc")]
        #pragma warning disable CS1591
        ValidityEndDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressID")]
        #pragma warning disable CS1591
        AddressID,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressID desc")]
        #pragma warning disable CS1591
        AddressIDDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "OrdinalNumber")]
        #pragma warning disable CS1591
        OrdinalNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "OrdinalNumber desc")]
        #pragma warning disable CS1591
        OrdinalNumberDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "IsDefaultURLAddress")]
        #pragma warning disable CS1591
        IsDefaultURLAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "IsDefaultURLAddress desc")]
        #pragma warning disable CS1591
        IsDefaultURLAddressDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "SearchURLAddress")]
        #pragma warning disable CS1591
        SearchURLAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "SearchURLAddress desc")]
        #pragma warning disable CS1591
        SearchURLAddressDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CommNumberIsNotUsed")]
        #pragma warning disable CS1591
        CommNumberIsNotUsed,
        #pragma warning restore CS1591
        [EnumMember(Value = "CommNumberIsNotUsed desc")]
        #pragma warning disable CS1591
        CommNumberIsNotUsedDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "URLFieldLength")]
        #pragma warning disable CS1591
        URLFieldLength,
        #pragma warning restore CS1591
        [EnumMember(Value = "URLFieldLength desc")]
        #pragma warning disable CS1591
        URLFieldLengthDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "WebsiteURL")]
        #pragma warning disable CS1591
        WebsiteURL,
        #pragma warning restore CS1591
        [EnumMember(Value = "WebsiteURL desc")]
        #pragma warning disable CS1591
        WebsiteURLDesc,
        #pragma warning restore CS1591
    }
}
