// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_BusinessPartnerWithBusinessPartner.To_BusinessPartnerAddress
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrderbyQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BusinessPartner")]
        #pragma warning disable CS1591
        BusinessPartner,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartner desc")]
        #pragma warning disable CS1591
        BusinessPartnerDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressID")]
        #pragma warning disable CS1591
        AddressID,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressID desc")]
        #pragma warning disable CS1591
        AddressIDDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "ValidityStartDate")]
        #pragma warning disable CS1591
        ValidityStartDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "ValidityStartDate desc")]
        #pragma warning disable CS1591
        ValidityStartDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "ValidityEndDate")]
        #pragma warning disable CS1591
        ValidityEndDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "ValidityEndDate desc")]
        #pragma warning disable CS1591
        ValidityEndDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "AuthorizationGroup")]
        #pragma warning disable CS1591
        AuthorizationGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "AuthorizationGroup desc")]
        #pragma warning disable CS1591
        AuthorizationGroupDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressUUID")]
        #pragma warning disable CS1591
        AddressUUID,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressUUID desc")]
        #pragma warning disable CS1591
        AddressUUIDDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "AdditionalStreetPrefixName")]
        #pragma warning disable CS1591
        AdditionalStreetPrefixName,
        #pragma warning restore CS1591
        [EnumMember(Value = "AdditionalStreetPrefixName desc")]
        #pragma warning disable CS1591
        AdditionalStreetPrefixNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "AdditionalStreetSuffixName")]
        #pragma warning disable CS1591
        AdditionalStreetSuffixName,
        #pragma warning restore CS1591
        [EnumMember(Value = "AdditionalStreetSuffixName desc")]
        #pragma warning disable CS1591
        AdditionalStreetSuffixNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressTimeZone")]
        #pragma warning disable CS1591
        AddressTimeZone,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressTimeZone desc")]
        #pragma warning disable CS1591
        AddressTimeZoneDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CareOfName")]
        #pragma warning disable CS1591
        CareOfName,
        #pragma warning restore CS1591
        [EnumMember(Value = "CareOfName desc")]
        #pragma warning disable CS1591
        CareOfNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CityCode")]
        #pragma warning disable CS1591
        CityCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "CityCode desc")]
        #pragma warning disable CS1591
        CityCodeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CityName")]
        #pragma warning disable CS1591
        CityName,
        #pragma warning restore CS1591
        [EnumMember(Value = "CityName desc")]
        #pragma warning disable CS1591
        CityNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CompanyPostalCode")]
        #pragma warning disable CS1591
        CompanyPostalCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "CompanyPostalCode desc")]
        #pragma warning disable CS1591
        CompanyPostalCodeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "Country")]
        #pragma warning disable CS1591
        Country,
        #pragma warning restore CS1591
        [EnumMember(Value = "Country desc")]
        #pragma warning disable CS1591
        CountryDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "County")]
        #pragma warning disable CS1591
        County,
        #pragma warning restore CS1591
        [EnumMember(Value = "County desc")]
        #pragma warning disable CS1591
        CountyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeliveryServiceNumber")]
        #pragma warning disable CS1591
        DeliveryServiceNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeliveryServiceNumber desc")]
        #pragma warning disable CS1591
        DeliveryServiceNumberDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeliveryServiceTypeCode")]
        #pragma warning disable CS1591
        DeliveryServiceTypeCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeliveryServiceTypeCode desc")]
        #pragma warning disable CS1591
        DeliveryServiceTypeCodeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "District")]
        #pragma warning disable CS1591
        District,
        #pragma warning restore CS1591
        [EnumMember(Value = "District desc")]
        #pragma warning disable CS1591
        DistrictDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "FormOfAddress")]
        #pragma warning disable CS1591
        FormOfAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "FormOfAddress desc")]
        #pragma warning disable CS1591
        FormOfAddressDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "FullName")]
        #pragma warning disable CS1591
        FullName,
        #pragma warning restore CS1591
        [EnumMember(Value = "FullName desc")]
        #pragma warning disable CS1591
        FullNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "HomeCityName")]
        #pragma warning disable CS1591
        HomeCityName,
        #pragma warning restore CS1591
        [EnumMember(Value = "HomeCityName desc")]
        #pragma warning disable CS1591
        HomeCityNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "HouseNumber")]
        #pragma warning disable CS1591
        HouseNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "HouseNumber desc")]
        #pragma warning disable CS1591
        HouseNumberDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "HouseNumberSupplementText")]
        #pragma warning disable CS1591
        HouseNumberSupplementText,
        #pragma warning restore CS1591
        [EnumMember(Value = "HouseNumberSupplementText desc")]
        #pragma warning disable CS1591
        HouseNumberSupplementTextDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "Language")]
        #pragma warning disable CS1591
        Language,
        #pragma warning restore CS1591
        [EnumMember(Value = "Language desc")]
        #pragma warning disable CS1591
        LanguageDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBox")]
        #pragma warning disable CS1591
        POBox,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBox desc")]
        #pragma warning disable CS1591
        POBoxDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxDeviatingCityName")]
        #pragma warning disable CS1591
        POBoxDeviatingCityName,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxDeviatingCityName desc")]
        #pragma warning disable CS1591
        POBoxDeviatingCityNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxDeviatingCountry")]
        #pragma warning disable CS1591
        POBoxDeviatingCountry,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxDeviatingCountry desc")]
        #pragma warning disable CS1591
        POBoxDeviatingCountryDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxDeviatingRegion")]
        #pragma warning disable CS1591
        POBoxDeviatingRegion,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxDeviatingRegion desc")]
        #pragma warning disable CS1591
        POBoxDeviatingRegionDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxIsWithoutNumber")]
        #pragma warning disable CS1591
        POBoxIsWithoutNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxIsWithoutNumber desc")]
        #pragma warning disable CS1591
        POBoxIsWithoutNumberDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxLobbyName")]
        #pragma warning disable CS1591
        POBoxLobbyName,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxLobbyName desc")]
        #pragma warning disable CS1591
        POBoxLobbyNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxPostalCode")]
        #pragma warning disable CS1591
        POBoxPostalCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxPostalCode desc")]
        #pragma warning disable CS1591
        POBoxPostalCodeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "Person")]
        #pragma warning disable CS1591
        Person,
        #pragma warning restore CS1591
        [EnumMember(Value = "Person desc")]
        #pragma warning disable CS1591
        PersonDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "PostalCode")]
        #pragma warning disable CS1591
        PostalCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "PostalCode desc")]
        #pragma warning disable CS1591
        PostalCodeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "PrfrdCommMediumType")]
        #pragma warning disable CS1591
        PrfrdCommMediumType,
        #pragma warning restore CS1591
        [EnumMember(Value = "PrfrdCommMediumType desc")]
        #pragma warning disable CS1591
        PrfrdCommMediumTypeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "Region")]
        #pragma warning disable CS1591
        Region,
        #pragma warning restore CS1591
        [EnumMember(Value = "Region desc")]
        #pragma warning disable CS1591
        RegionDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "StreetName")]
        #pragma warning disable CS1591
        StreetName,
        #pragma warning restore CS1591
        [EnumMember(Value = "StreetName desc")]
        #pragma warning disable CS1591
        StreetNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "StreetPrefixName")]
        #pragma warning disable CS1591
        StreetPrefixName,
        #pragma warning restore CS1591
        [EnumMember(Value = "StreetPrefixName desc")]
        #pragma warning disable CS1591
        StreetPrefixNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "StreetSuffixName")]
        #pragma warning disable CS1591
        StreetSuffixName,
        #pragma warning restore CS1591
        [EnumMember(Value = "StreetSuffixName desc")]
        #pragma warning disable CS1591
        StreetSuffixNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "TaxJurisdiction")]
        #pragma warning disable CS1591
        TaxJurisdiction,
        #pragma warning restore CS1591
        [EnumMember(Value = "TaxJurisdiction desc")]
        #pragma warning disable CS1591
        TaxJurisdictionDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "TransportZone")]
        #pragma warning disable CS1591
        TransportZone,
        #pragma warning restore CS1591
        [EnumMember(Value = "TransportZone desc")]
        #pragma warning disable CS1591
        TransportZoneDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressIDByExternalSystem")]
        #pragma warning disable CS1591
        AddressIDByExternalSystem,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressIDByExternalSystem desc")]
        #pragma warning disable CS1591
        AddressIDByExternalSystemDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CountyCode")]
        #pragma warning disable CS1591
        CountyCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "CountyCode desc")]
        #pragma warning disable CS1591
        CountyCodeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "TownshipCode")]
        #pragma warning disable CS1591
        TownshipCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "TownshipCode desc")]
        #pragma warning disable CS1591
        TownshipCodeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "TownshipName")]
        #pragma warning disable CS1591
        TownshipName,
        #pragma warning restore CS1591
        [EnumMember(Value = "TownshipName desc")]
        #pragma warning disable CS1591
        TownshipNameDesc,
        #pragma warning restore CS1591
    }
}
