// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_BPIntlAddressVersion
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSelectQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BusinessPartner")]
        #pragma warning disable CS1591
        BusinessPartner,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressID")]
        #pragma warning disable CS1591
        AddressID,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressRepresentationCode")]
        #pragma warning disable CS1591
        AddressRepresentationCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddresseeFullName")]
        #pragma warning disable CS1591
        AddresseeFullName,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressIDByExternalSystem")]
        #pragma warning disable CS1591
        AddressIDByExternalSystem,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressPersonID")]
        #pragma warning disable CS1591
        AddressPersonID,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressSearchTerm1")]
        #pragma warning disable CS1591
        AddressSearchTerm1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressSearchTerm2")]
        #pragma warning disable CS1591
        AddressSearchTerm2,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressTimeZone")]
        #pragma warning disable CS1591
        AddressTimeZone,
        #pragma warning restore CS1591
        [EnumMember(Value = "CareOfName")]
        #pragma warning disable CS1591
        CareOfName,
        #pragma warning restore CS1591
        [EnumMember(Value = "CityName")]
        #pragma warning disable CS1591
        CityName,
        #pragma warning restore CS1591
        [EnumMember(Value = "CityNumber")]
        #pragma warning disable CS1591
        CityNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "CompanyPostalCode")]
        #pragma warning disable CS1591
        CompanyPostalCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "Country")]
        #pragma warning disable CS1591
        Country,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeliveryServiceNumber")]
        #pragma warning disable CS1591
        DeliveryServiceNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeliveryServiceTypeCode")]
        #pragma warning disable CS1591
        DeliveryServiceTypeCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "DistrictName")]
        #pragma warning disable CS1591
        DistrictName,
        #pragma warning restore CS1591
        [EnumMember(Value = "FormOfAddress")]
        #pragma warning disable CS1591
        FormOfAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "HouseNumber")]
        #pragma warning disable CS1591
        HouseNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "HouseNumberSupplementText")]
        #pragma warning disable CS1591
        HouseNumberSupplementText,
        #pragma warning restore CS1591
        [EnumMember(Value = "Language")]
        #pragma warning disable CS1591
        Language,
        #pragma warning restore CS1591
        [EnumMember(Value = "OrganizationName1")]
        #pragma warning disable CS1591
        OrganizationName1,
        #pragma warning restore CS1591
        [EnumMember(Value = "OrganizationName2")]
        #pragma warning disable CS1591
        OrganizationName2,
        #pragma warning restore CS1591
        [EnumMember(Value = "OrganizationName3")]
        #pragma warning disable CS1591
        OrganizationName3,
        #pragma warning restore CS1591
        [EnumMember(Value = "OrganizationName4")]
        #pragma warning disable CS1591
        OrganizationName4,
        #pragma warning restore CS1591
        [EnumMember(Value = "PersonFamilyName")]
        #pragma warning disable CS1591
        PersonFamilyName,
        #pragma warning restore CS1591
        [EnumMember(Value = "PersonGivenName")]
        #pragma warning disable CS1591
        PersonGivenName,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBox")]
        #pragma warning disable CS1591
        POBox,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxDeviatingCityName")]
        #pragma warning disable CS1591
        POBoxDeviatingCityName,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxDeviatingCountry")]
        #pragma warning disable CS1591
        POBoxDeviatingCountry,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxDeviatingRegion")]
        #pragma warning disable CS1591
        POBoxDeviatingRegion,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxIsWithoutNumber")]
        #pragma warning disable CS1591
        POBoxIsWithoutNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxLobbyName")]
        #pragma warning disable CS1591
        POBoxLobbyName,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBoxPostalCode")]
        #pragma warning disable CS1591
        POBoxPostalCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "PostalCode")]
        #pragma warning disable CS1591
        PostalCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "PrfrdCommMediumType")]
        #pragma warning disable CS1591
        PrfrdCommMediumType,
        #pragma warning restore CS1591
        [EnumMember(Value = "Region")]
        #pragma warning disable CS1591
        Region,
        #pragma warning restore CS1591
        [EnumMember(Value = "SecondaryRegion")]
        #pragma warning disable CS1591
        SecondaryRegion,
        #pragma warning restore CS1591
        [EnumMember(Value = "SecondaryRegionName")]
        #pragma warning disable CS1591
        SecondaryRegionName,
        #pragma warning restore CS1591
        [EnumMember(Value = "StreetName")]
        #pragma warning disable CS1591
        StreetName,
        #pragma warning restore CS1591
        [EnumMember(Value = "StreetPrefixName1")]
        #pragma warning disable CS1591
        StreetPrefixName1,
        #pragma warning restore CS1591
        [EnumMember(Value = "StreetPrefixName2")]
        #pragma warning disable CS1591
        StreetPrefixName2,
        #pragma warning restore CS1591
        [EnumMember(Value = "StreetSuffixName1")]
        #pragma warning disable CS1591
        StreetSuffixName1,
        #pragma warning restore CS1591
        [EnumMember(Value = "StreetSuffixName2")]
        #pragma warning disable CS1591
        StreetSuffixName2,
        #pragma warning restore CS1591
        [EnumMember(Value = "TaxJurisdiction")]
        #pragma warning disable CS1591
        TaxJurisdiction,
        #pragma warning restore CS1591
        [EnumMember(Value = "TertiaryRegion")]
        #pragma warning disable CS1591
        TertiaryRegion,
        #pragma warning restore CS1591
        [EnumMember(Value = "TertiaryRegionName")]
        #pragma warning disable CS1591
        TertiaryRegionName,
        #pragma warning restore CS1591
        [EnumMember(Value = "TransportZone")]
        #pragma warning disable CS1591
        TransportZone,
        #pragma warning restore CS1591
        [EnumMember(Value = "VillageName")]
        #pragma warning disable CS1591
        VillageName,
        #pragma warning restore CS1591
    }
}
