// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using S4HANABusinessPartners.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr
{
    /// <summary>
    /// Builds and executes requests for operations under \A_BPContactPersonEmlAddr
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class A_BPContactPersonEmlAddrRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public A_BPContactPersonEmlAddrRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/A_BPContactPersonEmlAddr{?%24filter*,%24inlinecount*,%24orderby,%24select,%24skip*,%24top*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public A_BPContactPersonEmlAddrRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/A_BPContactPersonEmlAddr{?%24filter*,%24inlinecount*,%24orderby,%24select,%24skip*,%24top*}", rawUrl)
        {
        }
        /// <summary>
        ///  Gets the email address of a contact person
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrGetResponse?> GetAsA_BPContactPersonEmlAddrGetResponseAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrRequestBuilder.A_BPContactPersonEmlAddrRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrGetResponse> GetAsA_BPContactPersonEmlAddrGetResponseAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrRequestBuilder.A_BPContactPersonEmlAddrRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrGetResponse>(requestInfo, global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        ///  Gets the email address of a contact person
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
        [Obsolete("This method is obsolete. Use GetAsA_BPContactPersonEmlAddrGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrResponse?> GetAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrRequestBuilder.A_BPContactPersonEmlAddrRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrResponse> GetAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrRequestBuilder.A_BPContactPersonEmlAddrRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrResponse>(requestInfo, global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Add email address to a contact person 
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrPostResponse?> PostAsA_BPContactPersonEmlAddrPostResponseAsync(global::S4HANABusinessPartners.Client.Models.A_BPContactPersonEmlAddrTypeCreate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrPostResponse> PostAsA_BPContactPersonEmlAddrPostResponseAsync(global::S4HANABusinessPartners.Client.Models.A_BPContactPersonEmlAddrTypeCreate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrPostResponse>(requestInfo, global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Add email address to a contact person 
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
        [Obsolete("This method is obsolete. Use PostAsA_BPContactPersonEmlAddrPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrResponse?> PostAsync(global::S4HANABusinessPartners.Client.Models.A_BPContactPersonEmlAddrTypeCreate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrResponse> PostAsync(global::S4HANABusinessPartners.Client.Models.A_BPContactPersonEmlAddrTypeCreate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrResponse>(requestInfo, global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        ///  Gets the email address of a contact person
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrRequestBuilder.A_BPContactPersonEmlAddrRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrRequestBuilder.A_BPContactPersonEmlAddrRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Add email address to a contact person 
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::S4HANABusinessPartners.Client.Models.A_BPContactPersonEmlAddrTypeCreate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::S4HANABusinessPartners.Client.Models.A_BPContactPersonEmlAddrTypeCreate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrRequestBuilder WithUrl(string rawUrl)
        {
            return new global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        ///  Gets the email address of a contact person
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_BPContactPersonEmlAddrRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=64)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24filter")]
            public string? Filter { get; set; }
#nullable restore
#else
            [QueryParameter("%24filter")]
            public string Filter { get; set; }
#endif
            /// <summary>Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=67)</summary>
            [Obsolete("This property is deprecated, use InlinecountAsGetInlinecountQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24inlinecount")]
            public string? Inlinecount { get; set; }
#nullable restore
#else
            [QueryParameter("%24inlinecount")]
            public string Inlinecount { get; set; }
#endif
            /// <summary>Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=67)</summary>
            [QueryParameter("%24inlinecount")]
            public global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.GetInlinecountQueryParameterType? InlinecountAsGetInlinecountQueryParameterType { get; set; }
            /// <summary>Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=65)</summary>
            [Obsolete("This property is deprecated, use OrderbyAsGetOrderbyQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24orderby")]
            public string[]? Orderby { get; set; }
#nullable restore
#else
            [QueryParameter("%24orderby")]
            public string[] Orderby { get; set; }
#endif
            /// <summary>Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=65)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24orderby")]
            public global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.GetOrderbyQueryParameterType[]? OrderbyAsGetOrderbyQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("%24orderby")]
            public global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.GetOrderbyQueryParameterType[] OrderbyAsGetOrderbyQueryParameterType { get; set; }
#endif
            /// <summary>Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=68)</summary>
            [Obsolete("This property is deprecated, use SelectAsGetSelectQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24select")]
            public string[]? Select { get; set; }
#nullable restore
#else
            [QueryParameter("%24select")]
            public string[] Select { get; set; }
#endif
            /// <summary>Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=68)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24select")]
            public global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.GetSelectQueryParameterType[]? SelectAsGetSelectQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("%24select")]
            public global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.GetSelectQueryParameterType[] SelectAsGetSelectQueryParameterType { get; set; }
#endif
            /// <summary>Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=65)</summary>
            [QueryParameter("%24skip")]
            public int? Skip { get; set; }
            /// <summary>Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=66)</summary>
            [QueryParameter("%24top")]
            public int? Top { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_BPContactPersonEmlAddrRequestBuilderGetRequestConfiguration : RequestConfiguration<global::S4HANABusinessPartners.Client.A_BPContactPersonEmlAddr.A_BPContactPersonEmlAddrRequestBuilder.A_BPContactPersonEmlAddrRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_BPContactPersonEmlAddrRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
