// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_BusinessPartnerWithBusinessPartner.To_BPTaxCompliance
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrderbyQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BusinessPartner")]
        #pragma warning disable CS1591
        BusinessPartner,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartner desc")]
        #pragma warning disable CS1591
        BusinessPartnerDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceID")]
        #pragma warning disable CS1591
        BPTaxComplianceID,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceID desc")]
        #pragma warning disable CS1591
        BPTaxComplianceIDDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceType")]
        #pragma warning disable CS1591
        BPTaxComplianceType,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceType desc")]
        #pragma warning disable CS1591
        BPTaxComplianceTypeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceCountryRegion")]
        #pragma warning disable CS1591
        BPTaxComplianceCountryRegion,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceCountryRegion desc")]
        #pragma warning disable CS1591
        BPTaxComplianceCountryRegionDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceRegion")]
        #pragma warning disable CS1591
        BPTaxComplianceRegion,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceRegion desc")]
        #pragma warning disable CS1591
        BPTaxComplianceRegionDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceStatus")]
        #pragma warning disable CS1591
        BPTaxComplianceStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceStatus desc")]
        #pragma warning disable CS1591
        BPTaxComplianceStatusDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceStatusReason")]
        #pragma warning disable CS1591
        BPTaxComplianceStatusReason,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceStatusReason desc")]
        #pragma warning disable CS1591
        BPTaxComplianceStatusReasonDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceValidFromDate")]
        #pragma warning disable CS1591
        BPTaxComplianceValidFromDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceValidFromDate desc")]
        #pragma warning disable CS1591
        BPTaxComplianceValidFromDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceValidToDate")]
        #pragma warning disable CS1591
        BPTaxComplianceValidToDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceValidToDate desc")]
        #pragma warning disable CS1591
        BPTaxComplianceValidToDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceRatingDate")]
        #pragma warning disable CS1591
        BPTaxComplianceRatingDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceRatingDate desc")]
        #pragma warning disable CS1591
        BPTaxComplianceRatingDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceAgreementStatus")]
        #pragma warning disable CS1591
        BPTaxComplianceAgreementStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceAgreementStatus desc")]
        #pragma warning disable CS1591
        BPTaxComplianceAgreementStatusDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceAgreementDate")]
        #pragma warning disable CS1591
        BPTaxComplianceAgreementDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTaxComplianceAgreementDate desc")]
        #pragma warning disable CS1591
        BPTaxComplianceAgreementDateDesc,
        #pragma warning restore CS1591
    }
}
