// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.To_PartnerFunction;
using S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.To_SalesAreaTax;
using S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.To_SalesAreaText;
using S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.To_SlsAreaAddrDepdntInfo;
using S4HANABusinessPartners.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision
{
    /// <summary>
    /// Builds and executes requests for operations under \A_CustomerSalesArea(Customer=&apos;{Customer}&apos;,SalesOrganization=&apos;{SalesOrganization}&apos;,DistributionChannel=&apos;{DistributionChannel}&apos;,Division=&apos;{Division}&apos;)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The to_PartnerFunction property</summary>
        public global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.To_PartnerFunction.To_PartnerFunctionRequestBuilder To_PartnerFunction
        {
            get => new global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.To_PartnerFunction.To_PartnerFunctionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The to_SalesAreaTax property</summary>
        public global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.To_SalesAreaTax.To_SalesAreaTaxRequestBuilder To_SalesAreaTax
        {
            get => new global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.To_SalesAreaTax.To_SalesAreaTaxRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The to_SalesAreaText property</summary>
        public global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.To_SalesAreaText.To_SalesAreaTextRequestBuilder To_SalesAreaText
        {
            get => new global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.To_SalesAreaText.To_SalesAreaTextRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The to_SlsAreaAddrDepdntInfo property</summary>
        public global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.To_SlsAreaAddrDepdntInfo.To_SlsAreaAddrDepdntInfoRequestBuilder To_SlsAreaAddrDepdntInfo
        {
            get => new global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.To_SlsAreaAddrDepdntInfo.To_SlsAreaAddrDepdntInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="customer">Customer Number</param>
        /// <param name="distributionChannel">Distribution Channel</param>
        /// <param name="division">Division</param>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        /// <param name="salesOrganization">Sales Organization</param>
        public A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter, string customer = "", string distributionChannel = "", string division = "", string salesOrganization = "") : base(requestAdapter, "{+baseurl}/A_CustomerSalesArea(Customer='{Customer}',SalesOrganization='{SalesOrganization}',DistributionChannel='{DistributionChannel}',Division='{Division}'){?%24expand,%24select}", pathParameters)
        {
            if (!string.IsNullOrWhiteSpace(customer)) PathParameters.Add("Customer", customer);
            if (!string.IsNullOrWhiteSpace(distributionChannel)) PathParameters.Add("DistributionChannel", distributionChannel);
            if (!string.IsNullOrWhiteSpace(division)) PathParameters.Add("Division", division);
            if (!string.IsNullOrWhiteSpace(salesOrganization)) PathParameters.Add("SalesOrganization", salesOrganization);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/A_CustomerSalesArea(Customer='{Customer}',SalesOrganization='{SalesOrganization}',DistributionChannel='{DistributionChannel}',Division='{Division}'){?%24expand,%24select}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves customer sales area data by using Customer, SalesOrganization, DistributionChannel and Division.
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionGetResponse?> GetAsA_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionGetResponseAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilder.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionGetResponse> GetAsA_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionGetResponseAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilder.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionGetResponse>(requestInfo, global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves customer sales area data by using Customer, SalesOrganization, DistributionChannel and Division.
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
        [Obsolete("This method is obsolete. Use GetAsA_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionResponse?> GetAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilder.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionResponse> GetAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilder.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionResponse>(requestInfo, global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates sales data identified by Customer, SalesOrganization, DistributionChannel and Division.
        /// </summary>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PatchAsync(global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PatchAsync(global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves customer sales area data by using Customer, SalesOrganization, DistributionChannel and Division.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilder.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilder.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates sales data identified by Customer, SalesOrganization, DistributionChannel and Division.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilder WithUrl(string rawUrl)
        {
            return new global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves customer sales area data by using Customer, SalesOrganization, DistributionChannel and Division.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilderGetQueryParameters 
        {
            /// <summary>Expand related entities, see [Expand](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=63)</summary>
            [Obsolete("This property is deprecated, use ExpandAsGetExpandQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24expand")]
            public string[]? Expand { get; set; }
#nullable restore
#else
            [QueryParameter("%24expand")]
            public string[] Expand { get; set; }
#endif
            /// <summary>Expand related entities, see [Expand](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=63)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24expand")]
            public global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.GetExpandQueryParameterType[]? ExpandAsGetExpandQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("%24expand")]
            public global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.GetExpandQueryParameterType[] ExpandAsGetExpandQueryParameterType { get; set; }
#endif
            /// <summary>Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=68)</summary>
            [Obsolete("This property is deprecated, use SelectAsGetSelectQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24select")]
            public string[]? Select { get; set; }
#nullable restore
#else
            [QueryParameter("%24select")]
            public string[] Select { get; set; }
#endif
            /// <summary>Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=68)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24select")]
            public global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.GetSelectQueryParameterType[]? SelectAsGetSelectQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("%24select")]
            public global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.GetSelectQueryParameterType[] SelectAsGetSelectQueryParameterType { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilderGetRequestConfiguration : RequestConfiguration<global::S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilder.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionRequestBuilderPatchRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
