// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSelectQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Customer")]
        #pragma warning disable CS1591
        Customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "SalesOrganization")]
        #pragma warning disable CS1591
        SalesOrganization,
        #pragma warning restore CS1591
        [EnumMember(Value = "DistributionChannel")]
        #pragma warning disable CS1591
        DistributionChannel,
        #pragma warning restore CS1591
        [EnumMember(Value = "Division")]
        #pragma warning disable CS1591
        Division,
        #pragma warning restore CS1591
        [EnumMember(Value = "AccountByCustomer")]
        #pragma warning disable CS1591
        AccountByCustomer,
        #pragma warning restore CS1591
        [EnumMember(Value = "AuthorizationGroup")]
        #pragma warning disable CS1591
        AuthorizationGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "BillingIsBlockedForCustomer")]
        #pragma warning disable CS1591
        BillingIsBlockedForCustomer,
        #pragma warning restore CS1591
        [EnumMember(Value = "CompleteDeliveryIsDefined")]
        #pragma warning disable CS1591
        CompleteDeliveryIsDefined,
        #pragma warning restore CS1591
        [EnumMember(Value = "CreditControlArea")]
        #pragma warning disable CS1591
        CreditControlArea,
        #pragma warning restore CS1591
        [EnumMember(Value = "Currency")]
        #pragma warning disable CS1591
        Currency,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustIsRlvtForSettlmtMgmt")]
        #pragma warning disable CS1591
        CustIsRlvtForSettlmtMgmt,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerABCClassification")]
        #pragma warning disable CS1591
        CustomerABCClassification,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerAccountAssignmentGroup")]
        #pragma warning disable CS1591
        CustomerAccountAssignmentGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerGroup")]
        #pragma warning disable CS1591
        CustomerGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerIsRebateRelevant")]
        #pragma warning disable CS1591
        CustomerIsRebateRelevant,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerPaymentTerms")]
        #pragma warning disable CS1591
        CustomerPaymentTerms,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerPriceGroup")]
        #pragma warning disable CS1591
        CustomerPriceGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerPricingProcedure")]
        #pragma warning disable CS1591
        CustomerPricingProcedure,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustProdProposalProcedure")]
        #pragma warning disable CS1591
        CustProdProposalProcedure,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerStatisticsGroup")]
        #pragma warning disable CS1591
        CustomerStatisticsGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeliveryIsBlockedForCustomer")]
        #pragma warning disable CS1591
        DeliveryIsBlockedForCustomer,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeliveryPriority")]
        #pragma warning disable CS1591
        DeliveryPriority,
        #pragma warning restore CS1591
        [EnumMember(Value = "IncotermsClassification")]
        #pragma warning disable CS1591
        IncotermsClassification,
        #pragma warning restore CS1591
        [EnumMember(Value = "IncotermsLocation2")]
        #pragma warning disable CS1591
        IncotermsLocation2,
        #pragma warning restore CS1591
        [EnumMember(Value = "IncotermsVersion")]
        #pragma warning disable CS1591
        IncotermsVersion,
        #pragma warning restore CS1591
        [EnumMember(Value = "IncotermsLocation1")]
        #pragma warning disable CS1591
        IncotermsLocation1,
        #pragma warning restore CS1591
        [EnumMember(Value = "IncotermsSupChnLoc1AddlUUID")]
        #pragma warning disable CS1591
        IncotermsSupChnLoc1AddlUUID,
        #pragma warning restore CS1591
        [EnumMember(Value = "IncotermsSupChnLoc2AddlUUID")]
        #pragma warning disable CS1591
        IncotermsSupChnLoc2AddlUUID,
        #pragma warning restore CS1591
        [EnumMember(Value = "IncotermsSupChnDvtgLocAddlUUID")]
        #pragma warning disable CS1591
        IncotermsSupChnDvtgLocAddlUUID,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeletionIndicator")]
        #pragma warning disable CS1591
        DeletionIndicator,
        #pragma warning restore CS1591
        [EnumMember(Value = "IncotermsTransferLocation")]
        #pragma warning disable CS1591
        IncotermsTransferLocation,
        #pragma warning restore CS1591
        [EnumMember(Value = "InspSbstHasNoTimeOrQuantity")]
        #pragma warning disable CS1591
        InspSbstHasNoTimeOrQuantity,
        #pragma warning restore CS1591
        [EnumMember(Value = "InvoiceDate")]
        #pragma warning disable CS1591
        InvoiceDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "ItemOrderProbabilityInPercent")]
        #pragma warning disable CS1591
        ItemOrderProbabilityInPercent,
        #pragma warning restore CS1591
        [EnumMember(Value = "ManualInvoiceMaintIsRelevant")]
        #pragma warning disable CS1591
        ManualInvoiceMaintIsRelevant,
        #pragma warning restore CS1591
        [EnumMember(Value = "MaxNmbrOfPartialDelivery")]
        #pragma warning disable CS1591
        MaxNmbrOfPartialDelivery,
        #pragma warning restore CS1591
        [EnumMember(Value = "OrderCombinationIsAllowed")]
        #pragma warning disable CS1591
        OrderCombinationIsAllowed,
        #pragma warning restore CS1591
        [EnumMember(Value = "OrderIsBlockedForCustomer")]
        #pragma warning disable CS1591
        OrderIsBlockedForCustomer,
        #pragma warning restore CS1591
        [EnumMember(Value = "OverdelivTolrtdLmtRatioInPct")]
        #pragma warning disable CS1591
        OverdelivTolrtdLmtRatioInPct,
        #pragma warning restore CS1591
        [EnumMember(Value = "PartialDeliveryIsAllowed")]
        #pragma warning disable CS1591
        PartialDeliveryIsAllowed,
        #pragma warning restore CS1591
        [EnumMember(Value = "PriceListType")]
        #pragma warning disable CS1591
        PriceListType,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductUnitGroup")]
        #pragma warning disable CS1591
        ProductUnitGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProofOfDeliveryTimeValue")]
        #pragma warning disable CS1591
        ProofOfDeliveryTimeValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "SalesGroup")]
        #pragma warning disable CS1591
        SalesGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "SalesItemProposal")]
        #pragma warning disable CS1591
        SalesItemProposal,
        #pragma warning restore CS1591
        [EnumMember(Value = "SalesOffice")]
        #pragma warning disable CS1591
        SalesOffice,
        #pragma warning restore CS1591
        [EnumMember(Value = "ShippingCondition")]
        #pragma warning disable CS1591
        ShippingCondition,
        #pragma warning restore CS1591
        [EnumMember(Value = "SlsDocIsRlvtForProofOfDeliv")]
        #pragma warning disable CS1591
        SlsDocIsRlvtForProofOfDeliv,
        #pragma warning restore CS1591
        [EnumMember(Value = "SlsUnlmtdOvrdelivIsAllwd")]
        #pragma warning disable CS1591
        SlsUnlmtdOvrdelivIsAllwd,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplyingPlant")]
        #pragma warning disable CS1591
        SupplyingPlant,
        #pragma warning restore CS1591
        [EnumMember(Value = "SalesDistrict")]
        #pragma warning disable CS1591
        SalesDistrict,
        #pragma warning restore CS1591
        [EnumMember(Value = "UnderdelivTolrtdLmtRatioInPct")]
        #pragma warning disable CS1591
        UnderdelivTolrtdLmtRatioInPct,
        #pragma warning restore CS1591
        [EnumMember(Value = "InvoiceListSchedule")]
        #pragma warning disable CS1591
        InvoiceListSchedule,
        #pragma warning restore CS1591
        [EnumMember(Value = "ExchangeRateType")]
        #pragma warning disable CS1591
        ExchangeRateType,
        #pragma warning restore CS1591
        [EnumMember(Value = "AdditionalCustomerGroup1")]
        #pragma warning disable CS1591
        AdditionalCustomerGroup1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AdditionalCustomerGroup2")]
        #pragma warning disable CS1591
        AdditionalCustomerGroup2,
        #pragma warning restore CS1591
        [EnumMember(Value = "AdditionalCustomerGroup3")]
        #pragma warning disable CS1591
        AdditionalCustomerGroup3,
        #pragma warning restore CS1591
        [EnumMember(Value = "AdditionalCustomerGroup4")]
        #pragma warning disable CS1591
        AdditionalCustomerGroup4,
        #pragma warning restore CS1591
        [EnumMember(Value = "AdditionalCustomerGroup5")]
        #pragma warning disable CS1591
        AdditionalCustomerGroup5,
        #pragma warning restore CS1591
        [EnumMember(Value = "PaymentGuaranteeProcedure")]
        #pragma warning disable CS1591
        PaymentGuaranteeProcedure,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerAccountGroup")]
        #pragma warning disable CS1591
        CustomerAccountGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "to_PartnerFunction")]
        #pragma warning disable CS1591
        To_PartnerFunction,
        #pragma warning restore CS1591
        [EnumMember(Value = "to_SalesAreaTax")]
        #pragma warning disable CS1591
        To_SalesAreaTax,
        #pragma warning restore CS1591
        [EnumMember(Value = "to_SalesAreaText")]
        #pragma warning disable CS1591
        To_SalesAreaText,
        #pragma warning restore CS1591
        [EnumMember(Value = "to_SlsAreaAddrDepdntInfo")]
        #pragma warning disable CS1591
        To_SlsAreaAddrDepdntInfo,
        #pragma warning restore CS1591
    }
}
