// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.To_CompanyText;
using S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.To_Supplier;
using S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.To_SupplierDunning;
using S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.To_SupplierWithHoldingTax;
using S4HANABusinessPartners.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode
{
    /// <summary>
    /// Builds and executes requests for operations under \A_SupplierCompany(Supplier=&apos;{Supplier}&apos;,CompanyCode=&apos;{CompanyCode}&apos;)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The to_CompanyText property</summary>
        public global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.To_CompanyText.To_CompanyTextRequestBuilder To_CompanyText
        {
            get => new global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.To_CompanyText.To_CompanyTextRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The to_Supplier property</summary>
        public global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.To_Supplier.To_SupplierRequestBuilder To_Supplier
        {
            get => new global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.To_Supplier.To_SupplierRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The to_SupplierDunning property</summary>
        public global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.To_SupplierDunning.To_SupplierDunningRequestBuilder To_SupplierDunning
        {
            get => new global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.To_SupplierDunning.To_SupplierDunningRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The to_SupplierWithHoldingTax property</summary>
        public global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.To_SupplierWithHoldingTax.To_SupplierWithHoldingTaxRequestBuilder To_SupplierWithHoldingTax
        {
            get => new global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.To_SupplierWithHoldingTax.To_SupplierWithHoldingTaxRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="companyCode">Company Code</param>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        /// <param name="supplier">Account Number of Supplier</param>
        public A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter, string companyCode = "", string supplier = "") : base(requestAdapter, "{+baseurl}/A_SupplierCompany(Supplier='{Supplier}',CompanyCode='{CompanyCode}'){?%24expand,%24select}", pathParameters)
        {
            if (!string.IsNullOrWhiteSpace(companyCode)) PathParameters.Add("CompanyCode", companyCode);
            if (!string.IsNullOrWhiteSpace(supplier)) PathParameters.Add("Supplier", supplier);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/A_SupplierCompany(Supplier='{Supplier}',CompanyCode='{CompanyCode}'){?%24expand,%24select}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves supplier company data by using Supplier and CompanyCode fields.
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeGetResponse?> GetAsA_SupplierCompanyWithSupplierWithCompanyCodeGetResponseAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilder.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeGetResponse> GetAsA_SupplierCompanyWithSupplierWithCompanyCodeGetResponseAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilder.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeGetResponse>(requestInfo, global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves supplier company data by using Supplier and CompanyCode fields.
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
        [Obsolete("This method is obsolete. Use GetAsA_SupplierCompanyWithSupplierWithCompanyCodeGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeResponse?> GetAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilder.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeResponse> GetAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilder.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeResponse>(requestInfo, global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates supplier company data by using Supplier and CompanyCode fields.
        /// </summary>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PatchAsync(global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodePatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PatchAsync(global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodePatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves supplier company data by using Supplier and CompanyCode fields.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilder.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilder.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates supplier company data by using Supplier and CompanyCode fields.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodePatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodePatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves supplier company data by using Supplier and CompanyCode fields.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilderGetQueryParameters 
        {
            /// <summary>Expand related entities, see [Expand](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=63)</summary>
            [Obsolete("This property is deprecated, use ExpandAsGetExpandQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24expand")]
            public string[]? Expand { get; set; }
#nullable restore
#else
            [QueryParameter("%24expand")]
            public string[] Expand { get; set; }
#endif
            /// <summary>Expand related entities, see [Expand](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=63)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24expand")]
            public global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.GetExpandQueryParameterType[]? ExpandAsGetExpandQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("%24expand")]
            public global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.GetExpandQueryParameterType[] ExpandAsGetExpandQueryParameterType { get; set; }
#endif
            /// <summary>Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=68)</summary>
            [Obsolete("This property is deprecated, use SelectAsGetSelectQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24select")]
            public string[]? Select { get; set; }
#nullable restore
#else
            [QueryParameter("%24select")]
            public string[] Select { get; set; }
#endif
            /// <summary>Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=68)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24select")]
            public global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.GetSelectQueryParameterType[]? SelectAsGetSelectQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("%24select")]
            public global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.GetSelectQueryParameterType[] SelectAsGetSelectQueryParameterType { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilderGetRequestConfiguration : RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilder.A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_SupplierCompanyWithSupplierWithCompanyCodeRequestBuilderPatchRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
