// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_SupplierCompany
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrderbyQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Supplier")]
        #pragma warning disable CS1591
        Supplier,
        #pragma warning restore CS1591
        [EnumMember(Value = "Supplier desc")]
        #pragma warning disable CS1591
        SupplierDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CompanyCode")]
        #pragma warning disable CS1591
        CompanyCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "CompanyCode desc")]
        #pragma warning disable CS1591
        CompanyCodeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "AuthorizationGroup")]
        #pragma warning disable CS1591
        AuthorizationGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "AuthorizationGroup desc")]
        #pragma warning disable CS1591
        AuthorizationGroupDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CompanyCodeName")]
        #pragma warning disable CS1591
        CompanyCodeName,
        #pragma warning restore CS1591
        [EnumMember(Value = "CompanyCodeName desc")]
        #pragma warning disable CS1591
        CompanyCodeNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "PaymentBlockingReason")]
        #pragma warning disable CS1591
        PaymentBlockingReason,
        #pragma warning restore CS1591
        [EnumMember(Value = "PaymentBlockingReason desc")]
        #pragma warning disable CS1591
        PaymentBlockingReasonDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplierIsBlockedForPosting")]
        #pragma warning disable CS1591
        SupplierIsBlockedForPosting,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplierIsBlockedForPosting desc")]
        #pragma warning disable CS1591
        SupplierIsBlockedForPostingDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "AccountingClerk")]
        #pragma warning disable CS1591
        AccountingClerk,
        #pragma warning restore CS1591
        [EnumMember(Value = "AccountingClerk desc")]
        #pragma warning disable CS1591
        AccountingClerkDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "AccountingClerkFaxNumber")]
        #pragma warning disable CS1591
        AccountingClerkFaxNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "AccountingClerkFaxNumber desc")]
        #pragma warning disable CS1591
        AccountingClerkFaxNumberDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "AccountingClerkPhoneNumber")]
        #pragma warning disable CS1591
        AccountingClerkPhoneNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "AccountingClerkPhoneNumber desc")]
        #pragma warning disable CS1591
        AccountingClerkPhoneNumberDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplierClerk")]
        #pragma warning disable CS1591
        SupplierClerk,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplierClerk desc")]
        #pragma warning disable CS1591
        SupplierClerkDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplierClerkURL")]
        #pragma warning disable CS1591
        SupplierClerkURL,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplierClerkURL desc")]
        #pragma warning disable CS1591
        SupplierClerkURLDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "PaymentMethodsList")]
        #pragma warning disable CS1591
        PaymentMethodsList,
        #pragma warning restore CS1591
        [EnumMember(Value = "PaymentMethodsList desc")]
        #pragma warning disable CS1591
        PaymentMethodsListDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "PaymentReason")]
        #pragma warning disable CS1591
        PaymentReason,
        #pragma warning restore CS1591
        [EnumMember(Value = "PaymentReason desc")]
        #pragma warning disable CS1591
        PaymentReasonDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "PaymentTerms")]
        #pragma warning disable CS1591
        PaymentTerms,
        #pragma warning restore CS1591
        [EnumMember(Value = "PaymentTerms desc")]
        #pragma warning disable CS1591
        PaymentTermsDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "ClearCustomerSupplier")]
        #pragma warning disable CS1591
        ClearCustomerSupplier,
        #pragma warning restore CS1591
        [EnumMember(Value = "ClearCustomerSupplier desc")]
        #pragma warning disable CS1591
        ClearCustomerSupplierDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "IsToBeLocallyProcessed")]
        #pragma warning disable CS1591
        IsToBeLocallyProcessed,
        #pragma warning restore CS1591
        [EnumMember(Value = "IsToBeLocallyProcessed desc")]
        #pragma warning disable CS1591
        IsToBeLocallyProcessedDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "ItemIsToBePaidSeparately")]
        #pragma warning disable CS1591
        ItemIsToBePaidSeparately,
        #pragma warning restore CS1591
        [EnumMember(Value = "ItemIsToBePaidSeparately desc")]
        #pragma warning disable CS1591
        ItemIsToBePaidSeparatelyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "PaymentIsToBeSentByEDI")]
        #pragma warning disable CS1591
        PaymentIsToBeSentByEDI,
        #pragma warning restore CS1591
        [EnumMember(Value = "PaymentIsToBeSentByEDI desc")]
        #pragma warning disable CS1591
        PaymentIsToBeSentByEDIDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "HouseBank")]
        #pragma warning disable CS1591
        HouseBank,
        #pragma warning restore CS1591
        [EnumMember(Value = "HouseBank desc")]
        #pragma warning disable CS1591
        HouseBankDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CheckPaidDurationInDays")]
        #pragma warning disable CS1591
        CheckPaidDurationInDays,
        #pragma warning restore CS1591
        [EnumMember(Value = "CheckPaidDurationInDays desc")]
        #pragma warning disable CS1591
        CheckPaidDurationInDaysDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "Currency")]
        #pragma warning disable CS1591
        Currency,
        #pragma warning restore CS1591
        [EnumMember(Value = "Currency desc")]
        #pragma warning disable CS1591
        CurrencyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BillOfExchLmtAmtInCoCodeCrcy")]
        #pragma warning disable CS1591
        BillOfExchLmtAmtInCoCodeCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BillOfExchLmtAmtInCoCodeCrcy desc")]
        #pragma warning disable CS1591
        BillOfExchLmtAmtInCoCodeCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplierClerkIDBySupplier")]
        #pragma warning disable CS1591
        SupplierClerkIDBySupplier,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplierClerkIDBySupplier desc")]
        #pragma warning disable CS1591
        SupplierClerkIDBySupplierDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "ReconciliationAccount")]
        #pragma warning disable CS1591
        ReconciliationAccount,
        #pragma warning restore CS1591
        [EnumMember(Value = "ReconciliationAccount desc")]
        #pragma warning disable CS1591
        ReconciliationAccountDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "InterestCalculationCode")]
        #pragma warning disable CS1591
        InterestCalculationCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "InterestCalculationCode desc")]
        #pragma warning disable CS1591
        InterestCalculationCodeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "InterestCalculationDate")]
        #pragma warning disable CS1591
        InterestCalculationDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "InterestCalculationDate desc")]
        #pragma warning disable CS1591
        InterestCalculationDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "IntrstCalcFrequencyInMonths")]
        #pragma warning disable CS1591
        IntrstCalcFrequencyInMonths,
        #pragma warning restore CS1591
        [EnumMember(Value = "IntrstCalcFrequencyInMonths desc")]
        #pragma warning disable CS1591
        IntrstCalcFrequencyInMonthsDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplierHeadOffice")]
        #pragma warning disable CS1591
        SupplierHeadOffice,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplierHeadOffice desc")]
        #pragma warning disable CS1591
        SupplierHeadOfficeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlternativePayee")]
        #pragma warning disable CS1591
        AlternativePayee,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlternativePayee desc")]
        #pragma warning disable CS1591
        AlternativePayeeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "LayoutSortingRule")]
        #pragma warning disable CS1591
        LayoutSortingRule,
        #pragma warning restore CS1591
        [EnumMember(Value = "LayoutSortingRule desc")]
        #pragma warning disable CS1591
        LayoutSortingRuleDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "APARToleranceGroup")]
        #pragma warning disable CS1591
        APARToleranceGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "APARToleranceGroup desc")]
        #pragma warning disable CS1591
        APARToleranceGroupDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplierCertificationDate")]
        #pragma warning disable CS1591
        SupplierCertificationDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplierCertificationDate desc")]
        #pragma warning disable CS1591
        SupplierCertificationDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplierAccountNote")]
        #pragma warning disable CS1591
        SupplierAccountNote,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplierAccountNote desc")]
        #pragma warning disable CS1591
        SupplierAccountNoteDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "WithholdingTaxCountry")]
        #pragma warning disable CS1591
        WithholdingTaxCountry,
        #pragma warning restore CS1591
        [EnumMember(Value = "WithholdingTaxCountry desc")]
        #pragma warning disable CS1591
        WithholdingTaxCountryDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeletionIndicator")]
        #pragma warning disable CS1591
        DeletionIndicator,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeletionIndicator desc")]
        #pragma warning disable CS1591
        DeletionIndicatorDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CashPlanningGroup")]
        #pragma warning disable CS1591
        CashPlanningGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "CashPlanningGroup desc")]
        #pragma warning disable CS1591
        CashPlanningGroupDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "IsToBeCheckedForDuplicates")]
        #pragma warning disable CS1591
        IsToBeCheckedForDuplicates,
        #pragma warning restore CS1591
        [EnumMember(Value = "IsToBeCheckedForDuplicates desc")]
        #pragma warning disable CS1591
        IsToBeCheckedForDuplicatesDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "MinorityGroup")]
        #pragma warning disable CS1591
        MinorityGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "MinorityGroup desc")]
        #pragma warning disable CS1591
        MinorityGroupDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplierAccountGroup")]
        #pragma warning disable CS1591
        SupplierAccountGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplierAccountGroup desc")]
        #pragma warning disable CS1591
        SupplierAccountGroupDesc,
        #pragma warning restore CS1591
    }
}
