// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_BPContactToFuncAndDept
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSelectQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "RelationshipNumber")]
        #pragma warning disable CS1591
        RelationshipNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerCompany")]
        #pragma warning disable CS1591
        BusinessPartnerCompany,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerPerson")]
        #pragma warning disable CS1591
        BusinessPartnerPerson,
        #pragma warning restore CS1591
        [EnumMember(Value = "ValidityEndDate")]
        #pragma warning disable CS1591
        ValidityEndDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "ContactPersonAuthorityType")]
        #pragma warning disable CS1591
        ContactPersonAuthorityType,
        #pragma warning restore CS1591
        [EnumMember(Value = "ContactPersonDepartment")]
        #pragma warning disable CS1591
        ContactPersonDepartment,
        #pragma warning restore CS1591
        [EnumMember(Value = "ContactPersonDepartmentName")]
        #pragma warning disable CS1591
        ContactPersonDepartmentName,
        #pragma warning restore CS1591
        [EnumMember(Value = "ContactPersonFunction")]
        #pragma warning disable CS1591
        ContactPersonFunction,
        #pragma warning restore CS1591
        [EnumMember(Value = "ContactPersonFunctionName")]
        #pragma warning disable CS1591
        ContactPersonFunctionName,
        #pragma warning restore CS1591
        [EnumMember(Value = "ContactPersonRemarkText")]
        #pragma warning disable CS1591
        ContactPersonRemarkText,
        #pragma warning restore CS1591
        [EnumMember(Value = "ContactPersonVIPType")]
        #pragma warning disable CS1591
        ContactPersonVIPType,
        #pragma warning restore CS1591
        [EnumMember(Value = "EmailAddress")]
        #pragma warning disable CS1591
        EmailAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "FaxNumber")]
        #pragma warning disable CS1591
        FaxNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "FaxNumberExtension")]
        #pragma warning disable CS1591
        FaxNumberExtension,
        #pragma warning restore CS1591
        [EnumMember(Value = "PhoneNumber")]
        #pragma warning disable CS1591
        PhoneNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "PhoneNumberExtension")]
        #pragma warning disable CS1591
        PhoneNumberExtension,
        #pragma warning restore CS1591
        [EnumMember(Value = "RelationshipCategory")]
        #pragma warning disable CS1591
        RelationshipCategory,
        #pragma warning restore CS1591
    }
}
