// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_SupplierPurchasingOrgWithSupplierWithPurchasingOrganization.To_PurchasingOrgText
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrderbyQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Supplier")]
        #pragma warning disable CS1591
        Supplier,
        #pragma warning restore CS1591
        [EnumMember(Value = "Supplier desc")]
        #pragma warning disable CS1591
        SupplierDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "PurchasingOrganization")]
        #pragma warning disable CS1591
        PurchasingOrganization,
        #pragma warning restore CS1591
        [EnumMember(Value = "PurchasingOrganization desc")]
        #pragma warning disable CS1591
        PurchasingOrganizationDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "Language")]
        #pragma warning disable CS1591
        Language,
        #pragma warning restore CS1591
        [EnumMember(Value = "Language desc")]
        #pragma warning disable CS1591
        LanguageDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "LongTextID")]
        #pragma warning disable CS1591
        LongTextID,
        #pragma warning restore CS1591
        [EnumMember(Value = "LongTextID desc")]
        #pragma warning disable CS1591
        LongTextIDDesc,
        #pragma warning restore CS1591
    }
}
