// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_BusinessPartnerAlias
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrderbyQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BusinessPartner")]
        #pragma warning disable CS1591
        BusinessPartner,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartner desc")]
        #pragma warning disable CS1591
        BusinessPartnerDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPAliasPositionNumber")]
        #pragma warning disable CS1591
        BPAliasPositionNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPAliasPositionNumber desc")]
        #pragma warning disable CS1591
        BPAliasPositionNumberDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerAliasName")]
        #pragma warning disable CS1591
        BusinessPartnerAliasName,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerAliasName desc")]
        #pragma warning disable CS1591
        BusinessPartnerAliasNameDesc,
        #pragma warning restore CS1591
    }
}
