// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_BusinessPartnerRating
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSelectQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BusinessPartner")]
        #pragma warning disable CS1591
        BusinessPartner,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerRatingProcedure")]
        #pragma warning disable CS1591
        BusinessPartnerRatingProcedure,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPRatingValidityEndDate")]
        #pragma warning disable CS1591
        BPRatingValidityEndDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerRatingGrade")]
        #pragma warning disable CS1591
        BusinessPartnerRatingGrade,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerRatingTrend")]
        #pragma warning disable CS1591
        BusinessPartnerRatingTrend,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPRatingValidityStartDate")]
        #pragma warning disable CS1591
        BPRatingValidityStartDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPRatingCreationDate")]
        #pragma warning disable CS1591
        BPRatingCreationDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerRatingComment")]
        #pragma warning disable CS1591
        BusinessPartnerRatingComment,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerRatingIsAllowed")]
        #pragma warning disable CS1591
        BusinessPartnerRatingIsAllowed,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPRatingIsValidOnKeyDate")]
        #pragma warning disable CS1591
        BPRatingIsValidOnKeyDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerRatingKeyDate")]
        #pragma warning disable CS1591
        BusinessPartnerRatingKeyDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerRatingIsExpired")]
        #pragma warning disable CS1591
        BusinessPartnerRatingIsExpired,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPRatingLongComment")]
        #pragma warning disable CS1591
        BPRatingLongComment,
        #pragma warning restore CS1591
    }
}
