// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using S4HANABusinessPartners.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID
{
    /// <summary>
    /// Builds and executes requests for operations under \A_SupplierPurchasingOrgText(Supplier=&apos;{Supplier}&apos;,PurchasingOrganization=&apos;{PurchasingOrganization}&apos;,Language=&apos;{Language}&apos;,LongTextID=&apos;{LongTextID}&apos;)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="language">Language key</param>
        /// <param name="longTextID">Text ID</param>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="purchasingOrganization">Purchasing Organization</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        /// <param name="supplier">Account Number of Supplier</param>
        public A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter, string language = "", string longTextID = "", string purchasingOrganization = "", string supplier = "") : base(requestAdapter, "{+baseurl}/A_SupplierPurchasingOrgText(Supplier='{Supplier}',PurchasingOrganization='{PurchasingOrganization}',Language='{Language}',LongTextID='{LongTextID}'){?%24select}", pathParameters)
        {
            if (!string.IsNullOrWhiteSpace(language)) PathParameters.Add("Language", language);
            if (!string.IsNullOrWhiteSpace(longTextID)) PathParameters.Add("LongTextID", longTextID);
            if (!string.IsNullOrWhiteSpace(purchasingOrganization)) PathParameters.Add("PurchasingOrganization", purchasingOrganization);
            if (!string.IsNullOrWhiteSpace(supplier)) PathParameters.Add("Supplier", supplier);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/A_SupplierPurchasingOrgText(Supplier='{Supplier}',PurchasingOrganization='{PurchasingOrganization}',Language='{Language}',LongTextID='{LongTextID}'){?%24select}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes text data linked to purchasing organization by Supplier, PurchasingOrganization, Language, and LongTextID.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves supplier purchasing organization text data using Supplier, PurchasingOrganization, Language, and LongTextID
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDGetResponse?> GetAsA_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDGetResponseAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilder.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDGetResponse> GetAsA_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDGetResponseAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilder.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDGetResponse>(requestInfo, global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves supplier purchasing organization text data using Supplier, PurchasingOrganization, Language, and LongTextID
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
        [Obsolete("This method is obsolete. Use GetAsA_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDResponse?> GetAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilder.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDResponse> GetAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilder.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDResponse>(requestInfo, global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates text data linked to purchasing organization by using Supplier, PurchasingOrganization, Language, and LongTextID fields.
        /// </summary>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PatchAsync(global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PatchAsync(global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes text data linked to purchasing organization by Supplier, PurchasingOrganization, Language, and LongTextID.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retrieves supplier purchasing organization text data using Supplier, PurchasingOrganization, Language, and LongTextID
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilder.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilder.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates text data linked to purchasing organization by using Supplier, PurchasingOrganization, Language, and LongTextID fields.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilder WithUrl(string rawUrl)
        {
            return new global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Retrieves supplier purchasing organization text data using Supplier, PurchasingOrganization, Language, and LongTextID
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilderGetQueryParameters 
        {
            /// <summary>Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=68)</summary>
            [Obsolete("This property is deprecated, use SelectAsGetSelectQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24select")]
            public string[]? Select { get; set; }
#nullable restore
#else
            [QueryParameter("%24select")]
            public string[] Select { get; set; }
#endif
            /// <summary>Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=68)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24select")]
            public global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.GetSelectQueryParameterType[]? SelectAsGetSelectQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("%24select")]
            public global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.GetSelectQueryParameterType[] SelectAsGetSelectQueryParameterType { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilderGetRequestConfiguration : RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextID.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilder.A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_SupplierPurchasingOrgTextWithSupplierWithPurchasingOrganizationWithLanguageWithLongTextIDRequestBuilderPatchRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
