// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_BusinessPartnerWithBusinessPartner.To_BuPaIndustry
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrderbyQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "IndustrySector")]
        #pragma warning disable CS1591
        IndustrySector,
        #pragma warning restore CS1591
        [EnumMember(Value = "IndustrySector desc")]
        #pragma warning disable CS1591
        IndustrySectorDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "IndustrySystemType")]
        #pragma warning disable CS1591
        IndustrySystemType,
        #pragma warning restore CS1591
        [EnumMember(Value = "IndustrySystemType desc")]
        #pragma warning disable CS1591
        IndustrySystemTypeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartner")]
        #pragma warning disable CS1591
        BusinessPartner,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartner desc")]
        #pragma warning disable CS1591
        BusinessPartnerDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "IsStandardIndustry")]
        #pragma warning disable CS1591
        IsStandardIndustry,
        #pragma warning restore CS1591
        [EnumMember(Value = "IsStandardIndustry desc")]
        #pragma warning disable CS1591
        IsStandardIndustryDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "IndustryKeyDescription")]
        #pragma warning disable CS1591
        IndustryKeyDescription,
        #pragma warning restore CS1591
        [EnumMember(Value = "IndustryKeyDescription desc")]
        #pragma warning disable CS1591
        IndustryKeyDescriptionDesc,
        #pragma warning restore CS1591
    }
}
