// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_BusinessPartnerWithBusinessPartner.To_BPDataController
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSelectQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BusinessPartner")]
        #pragma warning disable CS1591
        BusinessPartner,
        #pragma warning restore CS1591
        [EnumMember(Value = "DataController")]
        #pragma warning disable CS1591
        DataController,
        #pragma warning restore CS1591
        [EnumMember(Value = "PurposeForPersonalData")]
        #pragma warning disable CS1591
        PurposeForPersonalData,
        #pragma warning restore CS1591
        [EnumMember(Value = "DataControlAssignmentStatus")]
        #pragma warning disable CS1591
        DataControlAssignmentStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPDataControllerIsDerived")]
        #pragma warning disable CS1591
        BPDataControllerIsDerived,
        #pragma warning restore CS1591
        [EnumMember(Value = "PurposeDerived")]
        #pragma warning disable CS1591
        PurposeDerived,
        #pragma warning restore CS1591
        [EnumMember(Value = "PurposeType")]
        #pragma warning disable CS1591
        PurposeType,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPurposeFlag")]
        #pragma warning disable CS1591
        BusinessPurposeFlag,
        #pragma warning restore CS1591
    }
}
