// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_BPFinancialServicesExtn
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrderbyQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BusinessPartner")]
        #pragma warning disable CS1591
        BusinessPartner,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartner desc")]
        #pragma warning disable CS1591
        BusinessPartnerDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerIsVIP")]
        #pragma warning disable CS1591
        BusinessPartnerIsVIP,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerIsVIP desc")]
        #pragma warning disable CS1591
        BusinessPartnerIsVIPDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "TradingPartner")]
        #pragma warning disable CS1591
        TradingPartner,
        #pragma warning restore CS1591
        [EnumMember(Value = "TradingPartner desc")]
        #pragma warning disable CS1591
        TradingPartnerDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "FactoryCalendar")]
        #pragma warning disable CS1591
        FactoryCalendar,
        #pragma warning restore CS1591
        [EnumMember(Value = "FactoryCalendar desc")]
        #pragma warning disable CS1591
        FactoryCalendarDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerOfficeCountry")]
        #pragma warning disable CS1591
        BusinessPartnerOfficeCountry,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerOfficeCountry desc")]
        #pragma warning disable CS1591
        BusinessPartnerOfficeCountryDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerOfficeRegion")]
        #pragma warning disable CS1591
        BusinessPartnerOfficeRegion,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerOfficeRegion desc")]
        #pragma warning disable CS1591
        BusinessPartnerOfficeRegionDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPRegisteredOfficeName")]
        #pragma warning disable CS1591
        BPRegisteredOfficeName,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPRegisteredOfficeName desc")]
        #pragma warning disable CS1591
        BPRegisteredOfficeNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPBalanceSheetCurrency")]
        #pragma warning disable CS1591
        BPBalanceSheetCurrency,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPBalanceSheetCurrency desc")]
        #pragma warning disable CS1591
        BPBalanceSheetCurrencyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPLastCptlIncrAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPLastCptlIncrAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPLastCptlIncrAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPLastCptlIncrAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPLastCapitalIncreaseYear")]
        #pragma warning disable CS1591
        BPLastCapitalIncreaseYear,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPLastCapitalIncreaseYear desc")]
        #pragma warning disable CS1591
        BPLastCapitalIncreaseYearDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPBalanceSheetDisplayType")]
        #pragma warning disable CS1591
        BPBalanceSheetDisplayType,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPBalanceSheetDisplayType desc")]
        #pragma warning disable CS1591
        BPBalanceSheetDisplayTypeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerCitizenship")]
        #pragma warning disable CS1591
        BusinessPartnerCitizenship,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerCitizenship desc")]
        #pragma warning disable CS1591
        BusinessPartnerCitizenshipDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPMaritalPropertyRegime")]
        #pragma warning disable CS1591
        BPMaritalPropertyRegime,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPMaritalPropertyRegime desc")]
        #pragma warning disable CS1591
        BPMaritalPropertyRegimeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerIncomeCurrency")]
        #pragma warning disable CS1591
        BusinessPartnerIncomeCurrency,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerIncomeCurrency desc")]
        #pragma warning disable CS1591
        BusinessPartnerIncomeCurrencyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPNumberOfChildren")]
        #pragma warning disable CS1591
        BPNumberOfChildren,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPNumberOfChildren desc")]
        #pragma warning disable CS1591
        BPNumberOfChildrenDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPNumberOfHouseholdMembers")]
        #pragma warning disable CS1591
        BPNumberOfHouseholdMembers,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPNumberOfHouseholdMembers desc")]
        #pragma warning disable CS1591
        BPNumberOfHouseholdMembersDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPAnnualNetIncAmtInIncomeCrcy")]
        #pragma warning disable CS1591
        BPAnnualNetIncAmtInIncomeCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPAnnualNetIncAmtInIncomeCrcy desc")]
        #pragma warning disable CS1591
        BPAnnualNetIncAmtInIncomeCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPMonthlyNetIncAmtInIncomeCrcy")]
        #pragma warning disable CS1591
        BPMonthlyNetIncAmtInIncomeCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPMonthlyNetIncAmtInIncomeCrcy desc")]
        #pragma warning disable CS1591
        BPMonthlyNetIncAmtInIncomeCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPAnnualNetIncomeYear")]
        #pragma warning disable CS1591
        BPAnnualNetIncomeYear,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPAnnualNetIncomeYear desc")]
        #pragma warning disable CS1591
        BPAnnualNetIncomeYearDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPMonthlyNetIncomeMonth")]
        #pragma warning disable CS1591
        BPMonthlyNetIncomeMonth,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPMonthlyNetIncomeMonth desc")]
        #pragma warning disable CS1591
        BPMonthlyNetIncomeMonthDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPMonthlyNetIncomeYear")]
        #pragma warning disable CS1591
        BPMonthlyNetIncomeYear,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPMonthlyNetIncomeYear desc")]
        #pragma warning disable CS1591
        BPMonthlyNetIncomeYearDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPPlaceOfDeathName")]
        #pragma warning disable CS1591
        BPPlaceOfDeathName,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPPlaceOfDeathName desc")]
        #pragma warning disable CS1591
        BPPlaceOfDeathNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerIsUnwanted")]
        #pragma warning disable CS1591
        CustomerIsUnwanted,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerIsUnwanted desc")]
        #pragma warning disable CS1591
        CustomerIsUnwantedDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "UndesirabilityReason")]
        #pragma warning disable CS1591
        UndesirabilityReason,
        #pragma warning restore CS1591
        [EnumMember(Value = "UndesirabilityReason desc")]
        #pragma warning disable CS1591
        UndesirabilityReasonDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "UndesirabilityComment")]
        #pragma warning disable CS1591
        UndesirabilityComment,
        #pragma warning restore CS1591
        [EnumMember(Value = "UndesirabilityComment desc")]
        #pragma warning disable CS1591
        UndesirabilityCommentDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "LastCustomerContactDate")]
        #pragma warning disable CS1591
        LastCustomerContactDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "LastCustomerContactDate desc")]
        #pragma warning disable CS1591
        LastCustomerContactDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPGroupingCharacter")]
        #pragma warning disable CS1591
        BPGroupingCharacter,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPGroupingCharacter desc")]
        #pragma warning disable CS1591
        BPGroupingCharacterDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPLetterSalutation")]
        #pragma warning disable CS1591
        BPLetterSalutation,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPLetterSalutation desc")]
        #pragma warning disable CS1591
        BPLetterSalutationDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerTargetGroup")]
        #pragma warning disable CS1591
        BusinessPartnerTargetGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerTargetGroup desc")]
        #pragma warning disable CS1591
        BusinessPartnerTargetGroupDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerEmployeeGroup")]
        #pragma warning disable CS1591
        BusinessPartnerEmployeeGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerEmployeeGroup desc")]
        #pragma warning disable CS1591
        BusinessPartnerEmployeeGroupDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerIsEmployee")]
        #pragma warning disable CS1591
        BusinessPartnerIsEmployee,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerIsEmployee desc")]
        #pragma warning disable CS1591
        BusinessPartnerIsEmployeeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTermnBusRelationsBankDate")]
        #pragma warning disable CS1591
        BPTermnBusRelationsBankDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPTermnBusRelationsBankDate desc")]
        #pragma warning disable CS1591
        BPTermnBusRelationsBankDateDesc,
        #pragma warning restore CS1591
    }
}
