// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_BPCreditWorthinessWithBusinessPartner
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSelectQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BusinessPartner")]
        #pragma warning disable CS1591
        BusinessPartner,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusPartCreditStanding")]
        #pragma warning disable CS1591
        BusPartCreditStanding,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPCreditStandingStatus")]
        #pragma warning disable CS1591
        BPCreditStandingStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "CreditRatingAgency")]
        #pragma warning disable CS1591
        CreditRatingAgency,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPCreditStandingComment")]
        #pragma warning disable CS1591
        BPCreditStandingComment,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPCreditStandingDate")]
        #pragma warning disable CS1591
        BPCreditStandingDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPCreditStandingRating")]
        #pragma warning disable CS1591
        BPCreditStandingRating,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPLegalProceedingStatus")]
        #pragma warning disable CS1591
        BPLegalProceedingStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPLglProceedingInitiationDate")]
        #pragma warning disable CS1591
        BPLglProceedingInitiationDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerIsUnderOath")]
        #pragma warning disable CS1591
        BusinessPartnerIsUnderOath,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerOathDate")]
        #pragma warning disable CS1591
        BusinessPartnerOathDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerIsBankrupt")]
        #pragma warning disable CS1591
        BusinessPartnerIsBankrupt,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerBankruptcyDate")]
        #pragma warning disable CS1591
        BusinessPartnerBankruptcyDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPForeclosureIsInitiated")]
        #pragma warning disable CS1591
        BPForeclosureIsInitiated,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPForeclosureDate")]
        #pragma warning disable CS1591
        BPForeclosureDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPCrdtWrthnssAccessChkIsActive")]
        #pragma warning disable CS1591
        BPCrdtWrthnssAccessChkIsActive,
        #pragma warning restore CS1591
    }
}
