// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_AddressPhoneNumber
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSelectQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "AddressID")]
        #pragma warning disable CS1591
        AddressID,
        #pragma warning restore CS1591
        [EnumMember(Value = "Person")]
        #pragma warning disable CS1591
        Person,
        #pragma warning restore CS1591
        [EnumMember(Value = "OrdinalNumber")]
        #pragma warning disable CS1591
        OrdinalNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "DestinationLocationCountry")]
        #pragma warning disable CS1591
        DestinationLocationCountry,
        #pragma warning restore CS1591
        [EnumMember(Value = "IsDefaultPhoneNumber")]
        #pragma warning disable CS1591
        IsDefaultPhoneNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "PhoneNumber")]
        #pragma warning disable CS1591
        PhoneNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "PhoneNumberExtension")]
        #pragma warning disable CS1591
        PhoneNumberExtension,
        #pragma warning restore CS1591
        [EnumMember(Value = "InternationalPhoneNumber")]
        #pragma warning disable CS1591
        InternationalPhoneNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "PhoneNumberType")]
        #pragma warning disable CS1591
        PhoneNumberType,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressCommunicationRemarkText")]
        #pragma warning disable CS1591
        AddressCommunicationRemarkText,
        #pragma warning restore CS1591
    }
}
