// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace S4HANABusinessPartners.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class A_BPFinancialServicesExtnType : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The BPAnnualNetIncAmtInIncomeCrcy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPAnnualNetIncAmtInIncomeCrcy { get; set; }
#nullable restore
#else
        public string BPAnnualNetIncAmtInIncomeCrcy { get; set; }
#endif
        /// <summary>Year of Net Annual Income</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPAnnualNetIncomeYear { get; set; }
#nullable restore
#else
        public string BPAnnualNetIncomeYear { get; set; }
#endif
        /// <summary>Balance Sheet Currency</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPBalanceSheetCurrency { get; set; }
#nullable restore
#else
        public string BPBalanceSheetCurrency { get; set; }
#endif
        /// <summary>Balance Sheet Display</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPBalanceSheetDisplayType { get; set; }
#nullable restore
#else
        public string BPBalanceSheetDisplayType { get; set; }
#endif
        /// <summary>Grouping Characteristic</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPGroupingCharacter { get; set; }
#nullable restore
#else
        public string BPGroupingCharacter { get; set; }
#endif
        /// <summary>Year of Last Capital Increase</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPLastCapitalIncreaseYear { get; set; }
#nullable restore
#else
        public string BPLastCapitalIncreaseYear { get; set; }
#endif
        /// <summary>Amount of last capital increase</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPLastCptlIncrAmtInBalShtCrcy { get; set; }
#nullable restore
#else
        public string BPLastCptlIncrAmtInBalShtCrcy { get; set; }
#endif
        /// <summary>The BPLetterSalutation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPLetterSalutation { get; set; }
#nullable restore
#else
        public string BPLetterSalutation { get; set; }
#endif
        /// <summary>Marital property regime</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPMaritalPropertyRegime { get; set; }
#nullable restore
#else
        public string BPMaritalPropertyRegime { get; set; }
#endif
        /// <summary>Monthly Net Income of Business Partner</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPMonthlyNetIncAmtInIncomeCrcy { get; set; }
#nullable restore
#else
        public string BPMonthlyNetIncAmtInIncomeCrcy { get; set; }
#endif
        /// <summary>Calendar Month of Monthly Net Income</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPMonthlyNetIncomeMonth { get; set; }
#nullable restore
#else
        public string BPMonthlyNetIncomeMonth { get; set; }
#endif
        /// <summary>Year of Monthly Net Income</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPMonthlyNetIncomeYear { get; set; }
#nullable restore
#else
        public string BPMonthlyNetIncomeYear { get; set; }
#endif
        /// <summary>Number of Children Belonging to the Business Partner</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPNumberOfChildren { get; set; }
#nullable restore
#else
        public string BPNumberOfChildren { get; set; }
#endif
        /// <summary>Number of People Living in the Household</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPNumberOfHouseholdMembers { get; set; }
#nullable restore
#else
        public string BPNumberOfHouseholdMembers { get; set; }
#endif
        /// <summary>Name of Place of Death of Natural Person</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPPlaceOfDeathName { get; set; }
#nullable restore
#else
        public string BPPlaceOfDeathName { get; set; }
#endif
        /// <summary>The BPRegisteredOfficeName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPRegisteredOfficeName { get; set; }
#nullable restore
#else
        public string BPRegisteredOfficeName { get; set; }
#endif
        /// <summary>Termination Date for Business Relations with the Bank</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPTermnBusRelationsBankDate { get; set; }
#nullable restore
#else
        public string BPTermnBusRelationsBankDate { get; set; }
#endif
        /// <summary>Business Partner Number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessPartner { get; set; }
#nullable restore
#else
        public string BusinessPartner { get; set; }
#endif
        /// <summary>The BusinessPartnerCitizenship property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessPartnerCitizenship { get; set; }
#nullable restore
#else
        public string BusinessPartnerCitizenship { get; set; }
#endif
        /// <summary>The BusinessPartnerEmployeeGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessPartnerEmployeeGroup { get; set; }
#nullable restore
#else
        public string BusinessPartnerEmployeeGroup { get; set; }
#endif
        /// <summary>Currency of Net Income</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessPartnerIncomeCurrency { get; set; }
#nullable restore
#else
        public string BusinessPartnerIncomeCurrency { get; set; }
#endif
        /// <summary>The BusinessPartnerIsEmployee property</summary>
        public bool? BusinessPartnerIsEmployee { get; set; }
        /// <summary>Business Partner Is VIP</summary>
        public bool? BusinessPartnerIsVIP { get; set; }
        /// <summary>Country/Region of Registered Office</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessPartnerOfficeCountry { get; set; }
#nullable restore
#else
        public string BusinessPartnerOfficeCountry { get; set; }
#endif
        /// <summary>Region of Registered Office</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessPartnerOfficeRegion { get; set; }
#nullable restore
#else
        public string BusinessPartnerOfficeRegion { get; set; }
#endif
        /// <summary>The BusinessPartnerTargetGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessPartnerTargetGroup { get; set; }
#nullable restore
#else
        public string BusinessPartnerTargetGroup { get; set; }
#endif
        /// <summary>The CustomerIsUnwanted property</summary>
        public bool? CustomerIsUnwanted { get; set; }
        /// <summary>Factory Calendar</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FactoryCalendar { get; set; }
#nullable restore
#else
        public string FactoryCalendar { get; set; }
#endif
        /// <summary>Date of Last Customer Contact</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastCustomerContactDate { get; set; }
#nullable restore
#else
        public string LastCustomerContactDate { get; set; }
#endif
        /// <summary>Company ID of Trading Partner</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TradingPartner { get; set; }
#nullable restore
#else
        public string TradingPartner { get; set; }
#endif
        /// <summary>Comment on Undesirability</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UndesirabilityComment { get; set; }
#nullable restore
#else
        public string UndesirabilityComment { get; set; }
#endif
        /// <summary>Reason for Undesirability</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UndesirabilityReason { get; set; }
#nullable restore
#else
        public string UndesirabilityReason { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.Models.A_BPFinancialServicesExtnType"/> and sets the default values.
        /// </summary>
        public A_BPFinancialServicesExtnType()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.Models.A_BPFinancialServicesExtnType"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::S4HANABusinessPartners.Client.Models.A_BPFinancialServicesExtnType CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::S4HANABusinessPartners.Client.Models.A_BPFinancialServicesExtnType();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "BPAnnualNetIncAmtInIncomeCrcy", n => { BPAnnualNetIncAmtInIncomeCrcy = n.GetStringValue(); } },
                { "BPAnnualNetIncomeYear", n => { BPAnnualNetIncomeYear = n.GetStringValue(); } },
                { "BPBalanceSheetCurrency", n => { BPBalanceSheetCurrency = n.GetStringValue(); } },
                { "BPBalanceSheetDisplayType", n => { BPBalanceSheetDisplayType = n.GetStringValue(); } },
                { "BPGroupingCharacter", n => { BPGroupingCharacter = n.GetStringValue(); } },
                { "BPLastCapitalIncreaseYear", n => { BPLastCapitalIncreaseYear = n.GetStringValue(); } },
                { "BPLastCptlIncrAmtInBalShtCrcy", n => { BPLastCptlIncrAmtInBalShtCrcy = n.GetStringValue(); } },
                { "BPLetterSalutation", n => { BPLetterSalutation = n.GetStringValue(); } },
                { "BPMaritalPropertyRegime", n => { BPMaritalPropertyRegime = n.GetStringValue(); } },
                { "BPMonthlyNetIncAmtInIncomeCrcy", n => { BPMonthlyNetIncAmtInIncomeCrcy = n.GetStringValue(); } },
                { "BPMonthlyNetIncomeMonth", n => { BPMonthlyNetIncomeMonth = n.GetStringValue(); } },
                { "BPMonthlyNetIncomeYear", n => { BPMonthlyNetIncomeYear = n.GetStringValue(); } },
                { "BPNumberOfChildren", n => { BPNumberOfChildren = n.GetStringValue(); } },
                { "BPNumberOfHouseholdMembers", n => { BPNumberOfHouseholdMembers = n.GetStringValue(); } },
                { "BPPlaceOfDeathName", n => { BPPlaceOfDeathName = n.GetStringValue(); } },
                { "BPRegisteredOfficeName", n => { BPRegisteredOfficeName = n.GetStringValue(); } },
                { "BPTermnBusRelationsBankDate", n => { BPTermnBusRelationsBankDate = n.GetStringValue(); } },
                { "BusinessPartner", n => { BusinessPartner = n.GetStringValue(); } },
                { "BusinessPartnerCitizenship", n => { BusinessPartnerCitizenship = n.GetStringValue(); } },
                { "BusinessPartnerEmployeeGroup", n => { BusinessPartnerEmployeeGroup = n.GetStringValue(); } },
                { "BusinessPartnerIncomeCurrency", n => { BusinessPartnerIncomeCurrency = n.GetStringValue(); } },
                { "BusinessPartnerIsEmployee", n => { BusinessPartnerIsEmployee = n.GetBoolValue(); } },
                { "BusinessPartnerIsVIP", n => { BusinessPartnerIsVIP = n.GetBoolValue(); } },
                { "BusinessPartnerOfficeCountry", n => { BusinessPartnerOfficeCountry = n.GetStringValue(); } },
                { "BusinessPartnerOfficeRegion", n => { BusinessPartnerOfficeRegion = n.GetStringValue(); } },
                { "BusinessPartnerTargetGroup", n => { BusinessPartnerTargetGroup = n.GetStringValue(); } },
                { "CustomerIsUnwanted", n => { CustomerIsUnwanted = n.GetBoolValue(); } },
                { "FactoryCalendar", n => { FactoryCalendar = n.GetStringValue(); } },
                { "LastCustomerContactDate", n => { LastCustomerContactDate = n.GetStringValue(); } },
                { "TradingPartner", n => { TradingPartner = n.GetStringValue(); } },
                { "UndesirabilityComment", n => { UndesirabilityComment = n.GetStringValue(); } },
                { "UndesirabilityReason", n => { UndesirabilityReason = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("BPAnnualNetIncAmtInIncomeCrcy", BPAnnualNetIncAmtInIncomeCrcy);
            writer.WriteStringValue("BPAnnualNetIncomeYear", BPAnnualNetIncomeYear);
            writer.WriteStringValue("BPBalanceSheetCurrency", BPBalanceSheetCurrency);
            writer.WriteStringValue("BPBalanceSheetDisplayType", BPBalanceSheetDisplayType);
            writer.WriteStringValue("BPGroupingCharacter", BPGroupingCharacter);
            writer.WriteStringValue("BPLastCapitalIncreaseYear", BPLastCapitalIncreaseYear);
            writer.WriteStringValue("BPLastCptlIncrAmtInBalShtCrcy", BPLastCptlIncrAmtInBalShtCrcy);
            writer.WriteStringValue("BPLetterSalutation", BPLetterSalutation);
            writer.WriteStringValue("BPMaritalPropertyRegime", BPMaritalPropertyRegime);
            writer.WriteStringValue("BPMonthlyNetIncAmtInIncomeCrcy", BPMonthlyNetIncAmtInIncomeCrcy);
            writer.WriteStringValue("BPMonthlyNetIncomeMonth", BPMonthlyNetIncomeMonth);
            writer.WriteStringValue("BPMonthlyNetIncomeYear", BPMonthlyNetIncomeYear);
            writer.WriteStringValue("BPNumberOfChildren", BPNumberOfChildren);
            writer.WriteStringValue("BPNumberOfHouseholdMembers", BPNumberOfHouseholdMembers);
            writer.WriteStringValue("BPPlaceOfDeathName", BPPlaceOfDeathName);
            writer.WriteStringValue("BPRegisteredOfficeName", BPRegisteredOfficeName);
            writer.WriteStringValue("BPTermnBusRelationsBankDate", BPTermnBusRelationsBankDate);
            writer.WriteStringValue("BusinessPartner", BusinessPartner);
            writer.WriteStringValue("BusinessPartnerCitizenship", BusinessPartnerCitizenship);
            writer.WriteStringValue("BusinessPartnerEmployeeGroup", BusinessPartnerEmployeeGroup);
            writer.WriteStringValue("BusinessPartnerIncomeCurrency", BusinessPartnerIncomeCurrency);
            writer.WriteBoolValue("BusinessPartnerIsEmployee", BusinessPartnerIsEmployee);
            writer.WriteBoolValue("BusinessPartnerIsVIP", BusinessPartnerIsVIP);
            writer.WriteStringValue("BusinessPartnerOfficeCountry", BusinessPartnerOfficeCountry);
            writer.WriteStringValue("BusinessPartnerOfficeRegion", BusinessPartnerOfficeRegion);
            writer.WriteStringValue("BusinessPartnerTargetGroup", BusinessPartnerTargetGroup);
            writer.WriteBoolValue("CustomerIsUnwanted", CustomerIsUnwanted);
            writer.WriteStringValue("FactoryCalendar", FactoryCalendar);
            writer.WriteStringValue("LastCustomerContactDate", LastCustomerContactDate);
            writer.WriteStringValue("TradingPartner", TradingPartner);
            writer.WriteStringValue("UndesirabilityComment", UndesirabilityComment);
            writer.WriteStringValue("UndesirabilityReason", UndesirabilityReason);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
