// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace S4HANABusinessPartners.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class A_BPContactToAddressTypeUpdate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Building (number or code)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactPersonBuilding { get; set; }
#nullable restore
#else
        public string ContactPersonBuilding { get; set; }
#endif
        /// <summary>Communication Method (Key) (Business Address Services)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactPersonPrfrdCommMedium { get; set; }
#nullable restore
#else
        public string ContactPersonPrfrdCommMedium { get; set; }
#endif
        /// <summary>The ContactRelationshipDepartment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactRelationshipDepartment { get; set; }
#nullable restore
#else
        public string ContactRelationshipDepartment { get; set; }
#endif
        /// <summary>The ContactRelationshipFunction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactRelationshipFunction { get; set; }
#nullable restore
#else
        public string ContactRelationshipFunction { get; set; }
#endif
        /// <summary>Short name for correspondence</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CorrespondenceShortName { get; set; }
#nullable restore
#else
        public string CorrespondenceShortName { get; set; }
#endif
        /// <summary>Floor in Building</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Floor { get; set; }
#nullable restore
#else
        public string Floor { get; set; }
#endif
        /// <summary>Internal Mail Postal Code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InhouseMail { get; set; }
#nullable restore
#else
        public string InhouseMail { get; set; }
#endif
        /// <summary>Indicator: Address is standard address</summary>
        public bool? IsDefaultAddress { get; set; }
        /// <summary>Room or Apartment Number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RoomNumber { get; set; }
#nullable restore
#else
        public string RoomNumber { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.Models.A_BPContactToAddressTypeUpdate"/> and sets the default values.
        /// </summary>
        public A_BPContactToAddressTypeUpdate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.Models.A_BPContactToAddressTypeUpdate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::S4HANABusinessPartners.Client.Models.A_BPContactToAddressTypeUpdate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::S4HANABusinessPartners.Client.Models.A_BPContactToAddressTypeUpdate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ContactPersonBuilding", n => { ContactPersonBuilding = n.GetStringValue(); } },
                { "ContactPersonPrfrdCommMedium", n => { ContactPersonPrfrdCommMedium = n.GetStringValue(); } },
                { "ContactRelationshipDepartment", n => { ContactRelationshipDepartment = n.GetStringValue(); } },
                { "ContactRelationshipFunction", n => { ContactRelationshipFunction = n.GetStringValue(); } },
                { "CorrespondenceShortName", n => { CorrespondenceShortName = n.GetStringValue(); } },
                { "Floor", n => { Floor = n.GetStringValue(); } },
                { "InhouseMail", n => { InhouseMail = n.GetStringValue(); } },
                { "IsDefaultAddress", n => { IsDefaultAddress = n.GetBoolValue(); } },
                { "RoomNumber", n => { RoomNumber = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("ContactPersonBuilding", ContactPersonBuilding);
            writer.WriteStringValue("ContactPersonPrfrdCommMedium", ContactPersonPrfrdCommMedium);
            writer.WriteStringValue("ContactRelationshipDepartment", ContactRelationshipDepartment);
            writer.WriteStringValue("ContactRelationshipFunction", ContactRelationshipFunction);
            writer.WriteStringValue("CorrespondenceShortName", CorrespondenceShortName);
            writer.WriteStringValue("Floor", Floor);
            writer.WriteStringValue("InhouseMail", InhouseMail);
            writer.WriteBoolValue("IsDefaultAddress", IsDefaultAddress);
            writer.WriteStringValue("RoomNumber", RoomNumber);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
