// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace S4HANABusinessPartners.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class A_BuPaAddressUsageTypeCreate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AddressID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressID { get; set; }
#nullable restore
#else
        public string AddressID { get; set; }
#endif
        /// <summary>The AddressUsage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressUsage { get; set; }
#nullable restore
#else
        public string AddressUsage { get; set; }
#endif
        /// <summary>The AuthorizationGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthorizationGroup { get; set; }
#nullable restore
#else
        public string AuthorizationGroup { get; set; }
#endif
        /// <summary>Business Partner Number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessPartner { get; set; }
#nullable restore
#else
        public string BusinessPartner { get; set; }
#endif
        /// <summary>Indicator: Standard Address Usage</summary>
        public bool? StandardUsage { get; set; }
        /// <summary>Validity End of a Business Partner Address Usage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ValidityEndDate { get; set; }
#nullable restore
#else
        public string ValidityEndDate { get; set; }
#endif
        /// <summary>Validity Start of a Business Partner Address Usage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ValidityStartDate { get; set; }
#nullable restore
#else
        public string ValidityStartDate { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.Models.A_BuPaAddressUsageTypeCreate"/> and sets the default values.
        /// </summary>
        public A_BuPaAddressUsageTypeCreate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.Models.A_BuPaAddressUsageTypeCreate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::S4HANABusinessPartners.Client.Models.A_BuPaAddressUsageTypeCreate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::S4HANABusinessPartners.Client.Models.A_BuPaAddressUsageTypeCreate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AddressID", n => { AddressID = n.GetStringValue(); } },
                { "AddressUsage", n => { AddressUsage = n.GetStringValue(); } },
                { "AuthorizationGroup", n => { AuthorizationGroup = n.GetStringValue(); } },
                { "BusinessPartner", n => { BusinessPartner = n.GetStringValue(); } },
                { "StandardUsage", n => { StandardUsage = n.GetBoolValue(); } },
                { "ValidityEndDate", n => { ValidityEndDate = n.GetStringValue(); } },
                { "ValidityStartDate", n => { ValidityStartDate = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AddressID", AddressID);
            writer.WriteStringValue("AddressUsage", AddressUsage);
            writer.WriteStringValue("AuthorizationGroup", AuthorizationGroup);
            writer.WriteStringValue("BusinessPartner", BusinessPartner);
            writer.WriteBoolValue("StandardUsage", StandardUsage);
            writer.WriteStringValue("ValidityEndDate", ValidityEndDate);
            writer.WriteStringValue("ValidityStartDate", ValidityStartDate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
