// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace S4HANABusinessPartners.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class A_CustomerWithHoldingTaxTypeUpdate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Authorization Group</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthorizationGroup { get; set; }
#nullable restore
#else
        public string AuthorizationGroup { get; set; }
#endif
        /// <summary>Date on Which Exemption Begins</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExemptionDateBegin { get; set; }
#nullable restore
#else
        public string ExemptionDateBegin { get; set; }
#endif
        /// <summary>Date on Which Exemption Ends</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExemptionDateEnd { get; set; }
#nullable restore
#else
        public string ExemptionDateEnd { get; set; }
#endif
        /// <summary>Reason for Exemption</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExemptionReason { get; set; }
#nullable restore
#else
        public string ExemptionReason { get; set; }
#endif
        /// <summary>Obligated to Withhold Tax From</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObligationDateBegin { get; set; }
#nullable restore
#else
        public string ObligationDateBegin { get; set; }
#endif
        /// <summary>Obligated to Withhold Tax Until</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObligationDateEnd { get; set; }
#nullable restore
#else
        public string ObligationDateEnd { get; set; }
#endif
        /// <summary>Type of Recipient</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecipientType { get; set; }
#nullable restore
#else
        public string RecipientType { get; set; }
#endif
        /// <summary>Indicator: Withholding Tax Agent?</summary>
        public bool? WithholdingTaxAgent { get; set; }
        /// <summary>Exemption Certificate Number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WithholdingTaxCertificate { get; set; }
#nullable restore
#else
        public string WithholdingTaxCertificate { get; set; }
#endif
        /// <summary>Withholding Tax Code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WithholdingTaxCode { get; set; }
#nullable restore
#else
        public string WithholdingTaxCode { get; set; }
#endif
        /// <summary>The WithholdingTaxExmptPercent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WithholdingTaxExmptPercent { get; set; }
#nullable restore
#else
        public string WithholdingTaxExmptPercent { get; set; }
#endif
        /// <summary>Withholding tax identification number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WithholdingTaxNumber { get; set; }
#nullable restore
#else
        public string WithholdingTaxNumber { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.Models.A_CustomerWithHoldingTaxTypeUpdate"/> and sets the default values.
        /// </summary>
        public A_CustomerWithHoldingTaxTypeUpdate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.Models.A_CustomerWithHoldingTaxTypeUpdate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::S4HANABusinessPartners.Client.Models.A_CustomerWithHoldingTaxTypeUpdate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::S4HANABusinessPartners.Client.Models.A_CustomerWithHoldingTaxTypeUpdate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AuthorizationGroup", n => { AuthorizationGroup = n.GetStringValue(); } },
                { "ExemptionDateBegin", n => { ExemptionDateBegin = n.GetStringValue(); } },
                { "ExemptionDateEnd", n => { ExemptionDateEnd = n.GetStringValue(); } },
                { "ExemptionReason", n => { ExemptionReason = n.GetStringValue(); } },
                { "ObligationDateBegin", n => { ObligationDateBegin = n.GetStringValue(); } },
                { "ObligationDateEnd", n => { ObligationDateEnd = n.GetStringValue(); } },
                { "RecipientType", n => { RecipientType = n.GetStringValue(); } },
                { "WithholdingTaxAgent", n => { WithholdingTaxAgent = n.GetBoolValue(); } },
                { "WithholdingTaxCertificate", n => { WithholdingTaxCertificate = n.GetStringValue(); } },
                { "WithholdingTaxCode", n => { WithholdingTaxCode = n.GetStringValue(); } },
                { "WithholdingTaxExmptPercent", n => { WithholdingTaxExmptPercent = n.GetStringValue(); } },
                { "WithholdingTaxNumber", n => { WithholdingTaxNumber = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AuthorizationGroup", AuthorizationGroup);
            writer.WriteStringValue("ExemptionDateBegin", ExemptionDateBegin);
            writer.WriteStringValue("ExemptionDateEnd", ExemptionDateEnd);
            writer.WriteStringValue("ExemptionReason", ExemptionReason);
            writer.WriteStringValue("ObligationDateBegin", ObligationDateBegin);
            writer.WriteStringValue("ObligationDateEnd", ObligationDateEnd);
            writer.WriteStringValue("RecipientType", RecipientType);
            writer.WriteBoolValue("WithholdingTaxAgent", WithholdingTaxAgent);
            writer.WriteStringValue("WithholdingTaxCertificate", WithholdingTaxCertificate);
            writer.WriteStringValue("WithholdingTaxCode", WithholdingTaxCode);
            writer.WriteStringValue("WithholdingTaxExmptPercent", WithholdingTaxExmptPercent);
            writer.WriteStringValue("WithholdingTaxNumber", WithholdingTaxNumber);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
