// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace S4HANABusinessPartners.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class A_CustSlsAreaAddrDepdntInfoType : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Business Partner Address Number (from BUT020)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressID { get; set; }
#nullable restore
#else
        public string AddressID { get; set; }
#endif
        /// <summary>Customer Number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Customer { get; set; }
#nullable restore
#else
        public string Customer { get; set; }
#endif
        /// <summary>Customer delivery block (sales area)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeliveryIsBlocked { get; set; }
#nullable restore
#else
        public string DeliveryIsBlocked { get; set; }
#endif
        /// <summary>The DistributionChannel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DistributionChannel { get; set; }
#nullable restore
#else
        public string DistributionChannel { get; set; }
#endif
        /// <summary>The Division property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Division { get; set; }
#nullable restore
#else
        public string Division { get; set; }
#endif
        /// <summary>Incoterms (Part 1)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IncotermsClassification { get; set; }
#nullable restore
#else
        public string IncotermsClassification { get; set; }
#endif
        /// <summary>The IncotermsLocation1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IncotermsLocation1 { get; set; }
#nullable restore
#else
        public string IncotermsLocation1 { get; set; }
#endif
        /// <summary>The IncotermsLocation2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IncotermsLocation2 { get; set; }
#nullable restore
#else
        public string IncotermsLocation2 { get; set; }
#endif
        /// <summary>The IncotermsSupChnDvtgLocAddlUUID property</summary>
        public Guid? IncotermsSupChnDvtgLocAddlUUID { get; set; }
        /// <summary>The IncotermsSupChnLoc1AddlUUID property</summary>
        public Guid? IncotermsSupChnLoc1AddlUUID { get; set; }
        /// <summary>The IncotermsSupChnLoc2AddlUUID property</summary>
        public Guid? IncotermsSupChnLoc2AddlUUID { get; set; }
        /// <summary>The IncotermsVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IncotermsVersion { get; set; }
#nullable restore
#else
        public string IncotermsVersion { get; set; }
#endif
        /// <summary>The SalesGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SalesGroup { get; set; }
#nullable restore
#else
        public string SalesGroup { get; set; }
#endif
        /// <summary>The SalesOffice property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SalesOffice { get; set; }
#nullable restore
#else
        public string SalesOffice { get; set; }
#endif
        /// <summary>The SalesOrganization property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SalesOrganization { get; set; }
#nullable restore
#else
        public string SalesOrganization { get; set; }
#endif
        /// <summary>The ShippingCondition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShippingCondition { get; set; }
#nullable restore
#else
        public string ShippingCondition { get; set; }
#endif
        /// <summary>Delivering Plant (Own or External)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SupplyingPlant { get; set; }
#nullable restore
#else
        public string SupplyingPlant { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.Models.A_CustSlsAreaAddrDepdntInfoType"/> and sets the default values.
        /// </summary>
        public A_CustSlsAreaAddrDepdntInfoType()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.Models.A_CustSlsAreaAddrDepdntInfoType"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::S4HANABusinessPartners.Client.Models.A_CustSlsAreaAddrDepdntInfoType CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::S4HANABusinessPartners.Client.Models.A_CustSlsAreaAddrDepdntInfoType();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AddressID", n => { AddressID = n.GetStringValue(); } },
                { "Customer", n => { Customer = n.GetStringValue(); } },
                { "DeliveryIsBlocked", n => { DeliveryIsBlocked = n.GetStringValue(); } },
                { "DistributionChannel", n => { DistributionChannel = n.GetStringValue(); } },
                { "Division", n => { Division = n.GetStringValue(); } },
                { "IncotermsClassification", n => { IncotermsClassification = n.GetStringValue(); } },
                { "IncotermsLocation1", n => { IncotermsLocation1 = n.GetStringValue(); } },
                { "IncotermsLocation2", n => { IncotermsLocation2 = n.GetStringValue(); } },
                { "IncotermsSupChnDvtgLocAddlUUID", n => { IncotermsSupChnDvtgLocAddlUUID = n.GetGuidValue(); } },
                { "IncotermsSupChnLoc1AddlUUID", n => { IncotermsSupChnLoc1AddlUUID = n.GetGuidValue(); } },
                { "IncotermsSupChnLoc2AddlUUID", n => { IncotermsSupChnLoc2AddlUUID = n.GetGuidValue(); } },
                { "IncotermsVersion", n => { IncotermsVersion = n.GetStringValue(); } },
                { "SalesGroup", n => { SalesGroup = n.GetStringValue(); } },
                { "SalesOffice", n => { SalesOffice = n.GetStringValue(); } },
                { "SalesOrganization", n => { SalesOrganization = n.GetStringValue(); } },
                { "ShippingCondition", n => { ShippingCondition = n.GetStringValue(); } },
                { "SupplyingPlant", n => { SupplyingPlant = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AddressID", AddressID);
            writer.WriteStringValue("Customer", Customer);
            writer.WriteStringValue("DeliveryIsBlocked", DeliveryIsBlocked);
            writer.WriteStringValue("DistributionChannel", DistributionChannel);
            writer.WriteStringValue("Division", Division);
            writer.WriteStringValue("IncotermsClassification", IncotermsClassification);
            writer.WriteStringValue("IncotermsLocation1", IncotermsLocation1);
            writer.WriteStringValue("IncotermsLocation2", IncotermsLocation2);
            writer.WriteGuidValue("IncotermsSupChnDvtgLocAddlUUID", IncotermsSupChnDvtgLocAddlUUID);
            writer.WriteGuidValue("IncotermsSupChnLoc1AddlUUID", IncotermsSupChnLoc1AddlUUID);
            writer.WriteGuidValue("IncotermsSupChnLoc2AddlUUID", IncotermsSupChnLoc2AddlUUID);
            writer.WriteStringValue("IncotermsVersion", IncotermsVersion);
            writer.WriteStringValue("SalesGroup", SalesGroup);
            writer.WriteStringValue("SalesOffice", SalesOffice);
            writer.WriteStringValue("SalesOrganization", SalesOrganization);
            writer.WriteStringValue("ShippingCondition", ShippingCondition);
            writer.WriteStringValue("SupplyingPlant", SupplyingPlant);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
