// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace S4HANABusinessPartners.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class A_CustomerSalesAreaTypeCreate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Shipper&apos;s (Our) Account Number at the Customer or Vendor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountByCustomer { get; set; }
#nullable restore
#else
        public string AccountByCustomer { get; set; }
#endif
        /// <summary>The AdditionalCustomerGroup1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdditionalCustomerGroup1 { get; set; }
#nullable restore
#else
        public string AdditionalCustomerGroup1 { get; set; }
#endif
        /// <summary>The AdditionalCustomerGroup2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdditionalCustomerGroup2 { get; set; }
#nullable restore
#else
        public string AdditionalCustomerGroup2 { get; set; }
#endif
        /// <summary>The AdditionalCustomerGroup3 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdditionalCustomerGroup3 { get; set; }
#nullable restore
#else
        public string AdditionalCustomerGroup3 { get; set; }
#endif
        /// <summary>The AdditionalCustomerGroup4 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdditionalCustomerGroup4 { get; set; }
#nullable restore
#else
        public string AdditionalCustomerGroup4 { get; set; }
#endif
        /// <summary>The AdditionalCustomerGroup5 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdditionalCustomerGroup5 { get; set; }
#nullable restore
#else
        public string AdditionalCustomerGroup5 { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AuthorizationGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthorizationGroup { get; set; }
#nullable restore
#else
        public string AuthorizationGroup { get; set; }
#endif
        /// <summary>Billing block for customer (sales and distribution)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingIsBlockedForCustomer { get; set; }
#nullable restore
#else
        public string BillingIsBlockedForCustomer { get; set; }
#endif
        /// <summary>Complete Delivery Defined for Each Sales Order</summary>
        public bool? CompleteDeliveryIsDefined { get; set; }
        /// <summary>The CreditControlArea property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreditControlArea { get; set; }
#nullable restore
#else
        public string CreditControlArea { get; set; }
#endif
        /// <summary>The Currency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>Indicator: Relevant for Settlement Management</summary>
        public bool? CustIsRlvtForSettlmtMgmt { get; set; }
        /// <summary>Customer Number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Customer { get; set; }
#nullable restore
#else
        public string Customer { get; set; }
#endif
        /// <summary>Customer classification (ABC analysis)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerABCClassification { get; set; }
#nullable restore
#else
        public string CustomerABCClassification { get; set; }
#endif
        /// <summary>Account Assignment Group for Customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerAccountAssignmentGroup { get; set; }
#nullable restore
#else
        public string CustomerAccountAssignmentGroup { get; set; }
#endif
        /// <summary>Customer Account Group</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerAccountGroup { get; set; }
#nullable restore
#else
        public string CustomerAccountGroup { get; set; }
#endif
        /// <summary>The CustomerGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerGroup { get; set; }
#nullable restore
#else
        public string CustomerGroup { get; set; }
#endif
        /// <summary>Indicator: Customer Is Rebate-Relevant</summary>
        public bool? CustomerIsRebateRelevant { get; set; }
        /// <summary>Terms of Payment Key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerPaymentTerms { get; set; }
#nullable restore
#else
        public string CustomerPaymentTerms { get; set; }
#endif
        /// <summary>The CustomerPriceGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerPriceGroup { get; set; }
#nullable restore
#else
        public string CustomerPriceGroup { get; set; }
#endif
        /// <summary>Customer Classification for Pricing Procedure Determination</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerPricingProcedure { get; set; }
#nullable restore
#else
        public string CustomerPricingProcedure { get; set; }
#endif
        /// <summary>Customer Statistics Group</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerStatisticsGroup { get; set; }
#nullable restore
#else
        public string CustomerStatisticsGroup { get; set; }
#endif
        /// <summary>Customer procedure for product proposal</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustProdProposalProcedure { get; set; }
#nullable restore
#else
        public string CustProdProposalProcedure { get; set; }
#endif
        /// <summary>Deletion flag for customer (sales level)</summary>
        public bool? DeletionIndicator { get; set; }
        /// <summary>Customer delivery block (sales area)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeliveryIsBlockedForCustomer { get; set; }
#nullable restore
#else
        public string DeliveryIsBlockedForCustomer { get; set; }
#endif
        /// <summary>The DeliveryPriority property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeliveryPriority { get; set; }
#nullable restore
#else
        public string DeliveryPriority { get; set; }
#endif
        /// <summary>The DistributionChannel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DistributionChannel { get; set; }
#nullable restore
#else
        public string DistributionChannel { get; set; }
#endif
        /// <summary>The Division property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Division { get; set; }
#nullable restore
#else
        public string Division { get; set; }
#endif
        /// <summary>The ExchangeRateType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExchangeRateType { get; set; }
#nullable restore
#else
        public string ExchangeRateType { get; set; }
#endif
        /// <summary>Incoterms (Part 1)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IncotermsClassification { get; set; }
#nullable restore
#else
        public string IncotermsClassification { get; set; }
#endif
        /// <summary>The IncotermsLocation1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IncotermsLocation1 { get; set; }
#nullable restore
#else
        public string IncotermsLocation1 { get; set; }
#endif
        /// <summary>The IncotermsLocation2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IncotermsLocation2 { get; set; }
#nullable restore
#else
        public string IncotermsLocation2 { get; set; }
#endif
        /// <summary>The IncotermsSupChnDvtgLocAddlUUID property</summary>
        public Guid? IncotermsSupChnDvtgLocAddlUUID { get; set; }
        /// <summary>The IncotermsSupChnLoc1AddlUUID property</summary>
        public Guid? IncotermsSupChnLoc1AddlUUID { get; set; }
        /// <summary>The IncotermsSupChnLoc2AddlUUID property</summary>
        public Guid? IncotermsSupChnLoc2AddlUUID { get; set; }
        /// <summary>The IncotermsTransferLocation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IncotermsTransferLocation { get; set; }
#nullable restore
#else
        public string IncotermsTransferLocation { get; set; }
#endif
        /// <summary>The IncotermsVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IncotermsVersion { get; set; }
#nullable restore
#else
        public string IncotermsVersion { get; set; }
#endif
        /// <summary>Relevant for price determination ID</summary>
        public bool? InspSbstHasNoTimeOrQuantity { get; set; }
        /// <summary>Invoice Dates (Calendar Identification)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceDate { get; set; }
#nullable restore
#else
        public string InvoiceDate { get; set; }
#endif
        /// <summary>Invoice List Schedule (calendar identification)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceListSchedule { get; set; }
#nullable restore
#else
        public string InvoiceListSchedule { get; set; }
#endif
        /// <summary>Order Probability of the Item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ItemOrderProbabilityInPercent { get; set; }
#nullable restore
#else
        public string ItemOrderProbabilityInPercent { get; set; }
#endif
        /// <summary>Manual Invoice Maintenance</summary>
        public bool? ManualInvoiceMaintIsRelevant { get; set; }
        /// <summary>Maximum Number of Partial Deliveries Allowed Per Item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaxNmbrOfPartialDelivery { get; set; }
#nullable restore
#else
        public string MaxNmbrOfPartialDelivery { get; set; }
#endif
        /// <summary>Order Combination Indicator</summary>
        public bool? OrderCombinationIsAllowed { get; set; }
        /// <summary>Customer order block (sales area)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrderIsBlockedForCustomer { get; set; }
#nullable restore
#else
        public string OrderIsBlockedForCustomer { get; set; }
#endif
        /// <summary>Overdelivery Tolerance</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OverdelivTolrtdLmtRatioInPct { get; set; }
#nullable restore
#else
        public string OverdelivTolrtdLmtRatioInPct { get; set; }
#endif
        /// <summary>Partial delivery at item level</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PartialDeliveryIsAllowed { get; set; }
#nullable restore
#else
        public string PartialDeliveryIsAllowed { get; set; }
#endif
        /// <summary>Customer payment guarantee procedure</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentGuaranteeProcedure { get; set; }
#nullable restore
#else
        public string PaymentGuaranteeProcedure { get; set; }
#endif
        /// <summary>The PriceListType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PriceListType { get; set; }
#nullable restore
#else
        public string PriceListType { get; set; }
#endif
        /// <summary>Unit of Measure Group</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductUnitGroup { get; set; }
#nullable restore
#else
        public string ProductUnitGroup { get; set; }
#endif
        /// <summary>Timeframe for Confirmation of POD</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProofOfDeliveryTimeValue { get; set; }
#nullable restore
#else
        public string ProofOfDeliveryTimeValue { get; set; }
#endif
        /// <summary>The SalesDistrict property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SalesDistrict { get; set; }
#nullable restore
#else
        public string SalesDistrict { get; set; }
#endif
        /// <summary>The SalesGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SalesGroup { get; set; }
#nullable restore
#else
        public string SalesGroup { get; set; }
#endif
        /// <summary>The SalesItemProposal property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SalesItemProposal { get; set; }
#nullable restore
#else
        public string SalesItemProposal { get; set; }
#endif
        /// <summary>The SalesOffice property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SalesOffice { get; set; }
#nullable restore
#else
        public string SalesOffice { get; set; }
#endif
        /// <summary>The SalesOrganization property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SalesOrganization { get; set; }
#nullable restore
#else
        public string SalesOrganization { get; set; }
#endif
        /// <summary>The ShippingCondition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShippingCondition { get; set; }
#nullable restore
#else
        public string ShippingCondition { get; set; }
#endif
        /// <summary>Relevant for POD processing</summary>
        public bool? SlsDocIsRlvtForProofOfDeliv { get; set; }
        /// <summary>Unlimited Overdelivery Allowed</summary>
        public bool? SlsUnlmtdOvrdelivIsAllwd { get; set; }
        /// <summary>Delivering Plant (Own or External)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SupplyingPlant { get; set; }
#nullable restore
#else
        public string SupplyingPlant { get; set; }
#endif
        /// <summary>The to_PartnerFunction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_PartnerFunction? ToPartnerFunction { get; set; }
#nullable restore
#else
        public global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_PartnerFunction ToPartnerFunction { get; set; }
#endif
        /// <summary>The to_SalesAreaTax property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_SalesAreaTax? ToSalesAreaTax { get; set; }
#nullable restore
#else
        public global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_SalesAreaTax ToSalesAreaTax { get; set; }
#endif
        /// <summary>The to_SalesAreaText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_SalesAreaText? ToSalesAreaText { get; set; }
#nullable restore
#else
        public global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_SalesAreaText ToSalesAreaText { get; set; }
#endif
        /// <summary>The to_SlsAreaAddrDepdntInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_SlsAreaAddrDepdntInfo? ToSlsAreaAddrDepdntInfo { get; set; }
#nullable restore
#else
        public global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_SlsAreaAddrDepdntInfo ToSlsAreaAddrDepdntInfo { get; set; }
#endif
        /// <summary>Underdelivery Tolerance</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnderdelivTolrtdLmtRatioInPct { get; set; }
#nullable restore
#else
        public string UnderdelivTolrtdLmtRatioInPct { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate"/> and sets the default values.
        /// </summary>
        public A_CustomerSalesAreaTypeCreate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AccountByCustomer", n => { AccountByCustomer = n.GetStringValue(); } },
                { "AdditionalCustomerGroup1", n => { AdditionalCustomerGroup1 = n.GetStringValue(); } },
                { "AdditionalCustomerGroup2", n => { AdditionalCustomerGroup2 = n.GetStringValue(); } },
                { "AdditionalCustomerGroup3", n => { AdditionalCustomerGroup3 = n.GetStringValue(); } },
                { "AdditionalCustomerGroup4", n => { AdditionalCustomerGroup4 = n.GetStringValue(); } },
                { "AdditionalCustomerGroup5", n => { AdditionalCustomerGroup5 = n.GetStringValue(); } },
                { "AuthorizationGroup", n => { AuthorizationGroup = n.GetStringValue(); } },
                { "BillingIsBlockedForCustomer", n => { BillingIsBlockedForCustomer = n.GetStringValue(); } },
                { "CompleteDeliveryIsDefined", n => { CompleteDeliveryIsDefined = n.GetBoolValue(); } },
                { "CreditControlArea", n => { CreditControlArea = n.GetStringValue(); } },
                { "Currency", n => { Currency = n.GetStringValue(); } },
                { "CustIsRlvtForSettlmtMgmt", n => { CustIsRlvtForSettlmtMgmt = n.GetBoolValue(); } },
                { "CustProdProposalProcedure", n => { CustProdProposalProcedure = n.GetStringValue(); } },
                { "Customer", n => { Customer = n.GetStringValue(); } },
                { "CustomerABCClassification", n => { CustomerABCClassification = n.GetStringValue(); } },
                { "CustomerAccountAssignmentGroup", n => { CustomerAccountAssignmentGroup = n.GetStringValue(); } },
                { "CustomerAccountGroup", n => { CustomerAccountGroup = n.GetStringValue(); } },
                { "CustomerGroup", n => { CustomerGroup = n.GetStringValue(); } },
                { "CustomerIsRebateRelevant", n => { CustomerIsRebateRelevant = n.GetBoolValue(); } },
                { "CustomerPaymentTerms", n => { CustomerPaymentTerms = n.GetStringValue(); } },
                { "CustomerPriceGroup", n => { CustomerPriceGroup = n.GetStringValue(); } },
                { "CustomerPricingProcedure", n => { CustomerPricingProcedure = n.GetStringValue(); } },
                { "CustomerStatisticsGroup", n => { CustomerStatisticsGroup = n.GetStringValue(); } },
                { "DeletionIndicator", n => { DeletionIndicator = n.GetBoolValue(); } },
                { "DeliveryIsBlockedForCustomer", n => { DeliveryIsBlockedForCustomer = n.GetStringValue(); } },
                { "DeliveryPriority", n => { DeliveryPriority = n.GetStringValue(); } },
                { "DistributionChannel", n => { DistributionChannel = n.GetStringValue(); } },
                { "Division", n => { Division = n.GetStringValue(); } },
                { "ExchangeRateType", n => { ExchangeRateType = n.GetStringValue(); } },
                { "IncotermsClassification", n => { IncotermsClassification = n.GetStringValue(); } },
                { "IncotermsLocation1", n => { IncotermsLocation1 = n.GetStringValue(); } },
                { "IncotermsLocation2", n => { IncotermsLocation2 = n.GetStringValue(); } },
                { "IncotermsSupChnDvtgLocAddlUUID", n => { IncotermsSupChnDvtgLocAddlUUID = n.GetGuidValue(); } },
                { "IncotermsSupChnLoc1AddlUUID", n => { IncotermsSupChnLoc1AddlUUID = n.GetGuidValue(); } },
                { "IncotermsSupChnLoc2AddlUUID", n => { IncotermsSupChnLoc2AddlUUID = n.GetGuidValue(); } },
                { "IncotermsTransferLocation", n => { IncotermsTransferLocation = n.GetStringValue(); } },
                { "IncotermsVersion", n => { IncotermsVersion = n.GetStringValue(); } },
                { "InspSbstHasNoTimeOrQuantity", n => { InspSbstHasNoTimeOrQuantity = n.GetBoolValue(); } },
                { "InvoiceDate", n => { InvoiceDate = n.GetStringValue(); } },
                { "InvoiceListSchedule", n => { InvoiceListSchedule = n.GetStringValue(); } },
                { "ItemOrderProbabilityInPercent", n => { ItemOrderProbabilityInPercent = n.GetStringValue(); } },
                { "ManualInvoiceMaintIsRelevant", n => { ManualInvoiceMaintIsRelevant = n.GetBoolValue(); } },
                { "MaxNmbrOfPartialDelivery", n => { MaxNmbrOfPartialDelivery = n.GetStringValue(); } },
                { "OrderCombinationIsAllowed", n => { OrderCombinationIsAllowed = n.GetBoolValue(); } },
                { "OrderIsBlockedForCustomer", n => { OrderIsBlockedForCustomer = n.GetStringValue(); } },
                { "OverdelivTolrtdLmtRatioInPct", n => { OverdelivTolrtdLmtRatioInPct = n.GetStringValue(); } },
                { "PartialDeliveryIsAllowed", n => { PartialDeliveryIsAllowed = n.GetStringValue(); } },
                { "PaymentGuaranteeProcedure", n => { PaymentGuaranteeProcedure = n.GetStringValue(); } },
                { "PriceListType", n => { PriceListType = n.GetStringValue(); } },
                { "ProductUnitGroup", n => { ProductUnitGroup = n.GetStringValue(); } },
                { "ProofOfDeliveryTimeValue", n => { ProofOfDeliveryTimeValue = n.GetStringValue(); } },
                { "SalesDistrict", n => { SalesDistrict = n.GetStringValue(); } },
                { "SalesGroup", n => { SalesGroup = n.GetStringValue(); } },
                { "SalesItemProposal", n => { SalesItemProposal = n.GetStringValue(); } },
                { "SalesOffice", n => { SalesOffice = n.GetStringValue(); } },
                { "SalesOrganization", n => { SalesOrganization = n.GetStringValue(); } },
                { "ShippingCondition", n => { ShippingCondition = n.GetStringValue(); } },
                { "SlsDocIsRlvtForProofOfDeliv", n => { SlsDocIsRlvtForProofOfDeliv = n.GetBoolValue(); } },
                { "SlsUnlmtdOvrdelivIsAllwd", n => { SlsUnlmtdOvrdelivIsAllwd = n.GetBoolValue(); } },
                { "SupplyingPlant", n => { SupplyingPlant = n.GetStringValue(); } },
                { "to_PartnerFunction", n => { ToPartnerFunction = n.GetObjectValue<global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_PartnerFunction>(global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_PartnerFunction.CreateFromDiscriminatorValue); } },
                { "to_SalesAreaTax", n => { ToSalesAreaTax = n.GetObjectValue<global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_SalesAreaTax>(global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_SalesAreaTax.CreateFromDiscriminatorValue); } },
                { "to_SalesAreaText", n => { ToSalesAreaText = n.GetObjectValue<global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_SalesAreaText>(global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_SalesAreaText.CreateFromDiscriminatorValue); } },
                { "to_SlsAreaAddrDepdntInfo", n => { ToSlsAreaAddrDepdntInfo = n.GetObjectValue<global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_SlsAreaAddrDepdntInfo>(global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_SlsAreaAddrDepdntInfo.CreateFromDiscriminatorValue); } },
                { "UnderdelivTolrtdLmtRatioInPct", n => { UnderdelivTolrtdLmtRatioInPct = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AccountByCustomer", AccountByCustomer);
            writer.WriteStringValue("AdditionalCustomerGroup1", AdditionalCustomerGroup1);
            writer.WriteStringValue("AdditionalCustomerGroup2", AdditionalCustomerGroup2);
            writer.WriteStringValue("AdditionalCustomerGroup3", AdditionalCustomerGroup3);
            writer.WriteStringValue("AdditionalCustomerGroup4", AdditionalCustomerGroup4);
            writer.WriteStringValue("AdditionalCustomerGroup5", AdditionalCustomerGroup5);
            writer.WriteStringValue("AuthorizationGroup", AuthorizationGroup);
            writer.WriteStringValue("BillingIsBlockedForCustomer", BillingIsBlockedForCustomer);
            writer.WriteBoolValue("CompleteDeliveryIsDefined", CompleteDeliveryIsDefined);
            writer.WriteStringValue("CreditControlArea", CreditControlArea);
            writer.WriteStringValue("Currency", Currency);
            writer.WriteBoolValue("CustIsRlvtForSettlmtMgmt", CustIsRlvtForSettlmtMgmt);
            writer.WriteStringValue("Customer", Customer);
            writer.WriteStringValue("CustomerABCClassification", CustomerABCClassification);
            writer.WriteStringValue("CustomerAccountAssignmentGroup", CustomerAccountAssignmentGroup);
            writer.WriteStringValue("CustomerAccountGroup", CustomerAccountGroup);
            writer.WriteStringValue("CustomerGroup", CustomerGroup);
            writer.WriteBoolValue("CustomerIsRebateRelevant", CustomerIsRebateRelevant);
            writer.WriteStringValue("CustomerPaymentTerms", CustomerPaymentTerms);
            writer.WriteStringValue("CustomerPriceGroup", CustomerPriceGroup);
            writer.WriteStringValue("CustomerPricingProcedure", CustomerPricingProcedure);
            writer.WriteStringValue("CustomerStatisticsGroup", CustomerStatisticsGroup);
            writer.WriteStringValue("CustProdProposalProcedure", CustProdProposalProcedure);
            writer.WriteBoolValue("DeletionIndicator", DeletionIndicator);
            writer.WriteStringValue("DeliveryIsBlockedForCustomer", DeliveryIsBlockedForCustomer);
            writer.WriteStringValue("DeliveryPriority", DeliveryPriority);
            writer.WriteStringValue("DistributionChannel", DistributionChannel);
            writer.WriteStringValue("Division", Division);
            writer.WriteStringValue("ExchangeRateType", ExchangeRateType);
            writer.WriteStringValue("IncotermsClassification", IncotermsClassification);
            writer.WriteStringValue("IncotermsLocation1", IncotermsLocation1);
            writer.WriteStringValue("IncotermsLocation2", IncotermsLocation2);
            writer.WriteGuidValue("IncotermsSupChnDvtgLocAddlUUID", IncotermsSupChnDvtgLocAddlUUID);
            writer.WriteGuidValue("IncotermsSupChnLoc1AddlUUID", IncotermsSupChnLoc1AddlUUID);
            writer.WriteGuidValue("IncotermsSupChnLoc2AddlUUID", IncotermsSupChnLoc2AddlUUID);
            writer.WriteStringValue("IncotermsTransferLocation", IncotermsTransferLocation);
            writer.WriteStringValue("IncotermsVersion", IncotermsVersion);
            writer.WriteBoolValue("InspSbstHasNoTimeOrQuantity", InspSbstHasNoTimeOrQuantity);
            writer.WriteStringValue("InvoiceDate", InvoiceDate);
            writer.WriteStringValue("InvoiceListSchedule", InvoiceListSchedule);
            writer.WriteStringValue("ItemOrderProbabilityInPercent", ItemOrderProbabilityInPercent);
            writer.WriteBoolValue("ManualInvoiceMaintIsRelevant", ManualInvoiceMaintIsRelevant);
            writer.WriteStringValue("MaxNmbrOfPartialDelivery", MaxNmbrOfPartialDelivery);
            writer.WriteBoolValue("OrderCombinationIsAllowed", OrderCombinationIsAllowed);
            writer.WriteStringValue("OrderIsBlockedForCustomer", OrderIsBlockedForCustomer);
            writer.WriteStringValue("OverdelivTolrtdLmtRatioInPct", OverdelivTolrtdLmtRatioInPct);
            writer.WriteStringValue("PartialDeliveryIsAllowed", PartialDeliveryIsAllowed);
            writer.WriteStringValue("PaymentGuaranteeProcedure", PaymentGuaranteeProcedure);
            writer.WriteStringValue("PriceListType", PriceListType);
            writer.WriteStringValue("ProductUnitGroup", ProductUnitGroup);
            writer.WriteStringValue("ProofOfDeliveryTimeValue", ProofOfDeliveryTimeValue);
            writer.WriteStringValue("SalesDistrict", SalesDistrict);
            writer.WriteStringValue("SalesGroup", SalesGroup);
            writer.WriteStringValue("SalesItemProposal", SalesItemProposal);
            writer.WriteStringValue("SalesOffice", SalesOffice);
            writer.WriteStringValue("SalesOrganization", SalesOrganization);
            writer.WriteStringValue("ShippingCondition", ShippingCondition);
            writer.WriteBoolValue("SlsDocIsRlvtForProofOfDeliv", SlsDocIsRlvtForProofOfDeliv);
            writer.WriteBoolValue("SlsUnlmtdOvrdelivIsAllwd", SlsUnlmtdOvrdelivIsAllwd);
            writer.WriteStringValue("SupplyingPlant", SupplyingPlant);
            writer.WriteObjectValue<global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_PartnerFunction>("to_PartnerFunction", ToPartnerFunction);
            writer.WriteObjectValue<global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_SalesAreaTax>("to_SalesAreaTax", ToSalesAreaTax);
            writer.WriteObjectValue<global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_SalesAreaText>("to_SalesAreaText", ToSalesAreaText);
            writer.WriteObjectValue<global::S4HANABusinessPartners.Client.Models.A_CustomerSalesAreaTypeCreate_to_SlsAreaAddrDepdntInfo>("to_SlsAreaAddrDepdntInfo", ToSlsAreaAddrDepdntInfo);
            writer.WriteStringValue("UnderdelivTolrtdLmtRatioInPct", UnderdelivTolrtdLmtRatioInPct);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
