// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace S4HANABusinessPartners.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class A_CustSalesPartnerFuncTypeUpdate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Business Partner Address Number (from BUT020)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressID { get; set; }
#nullable restore
#else
        public string AddressID { get; set; }
#endif
        /// <summary>Authorization Group</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthorizationGroup { get; set; }
#nullable restore
#else
        public string AuthorizationGroup { get; set; }
#endif
        /// <summary>Account Number of Supplier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BPCustomerNumber { get; set; }
#nullable restore
#else
        public string BPCustomerNumber { get; set; }
#endif
        /// <summary>Number of Contact Person</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactPerson { get; set; }
#nullable restore
#else
        public string ContactPerson { get; set; }
#endif
        /// <summary>Customer description of partner (plant, storage location)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerPartnerDescription { get; set; }
#nullable restore
#else
        public string CustomerPartnerDescription { get; set; }
#endif
        /// <summary>The DefaultPartner property</summary>
        public bool? DefaultPartner { get; set; }
        /// <summary>The PersonnelNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PersonnelNumber { get; set; }
#nullable restore
#else
        public string PersonnelNumber { get; set; }
#endif
        /// <summary>Account Number of Supplier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Supplier { get; set; }
#nullable restore
#else
        public string Supplier { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.Models.A_CustSalesPartnerFuncTypeUpdate"/> and sets the default values.
        /// </summary>
        public A_CustSalesPartnerFuncTypeUpdate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.Models.A_CustSalesPartnerFuncTypeUpdate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::S4HANABusinessPartners.Client.Models.A_CustSalesPartnerFuncTypeUpdate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::S4HANABusinessPartners.Client.Models.A_CustSalesPartnerFuncTypeUpdate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AddressID", n => { AddressID = n.GetStringValue(); } },
                { "AuthorizationGroup", n => { AuthorizationGroup = n.GetStringValue(); } },
                { "BPCustomerNumber", n => { BPCustomerNumber = n.GetStringValue(); } },
                { "ContactPerson", n => { ContactPerson = n.GetStringValue(); } },
                { "CustomerPartnerDescription", n => { CustomerPartnerDescription = n.GetStringValue(); } },
                { "DefaultPartner", n => { DefaultPartner = n.GetBoolValue(); } },
                { "PersonnelNumber", n => { PersonnelNumber = n.GetStringValue(); } },
                { "Supplier", n => { Supplier = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AddressID", AddressID);
            writer.WriteStringValue("AuthorizationGroup", AuthorizationGroup);
            writer.WriteStringValue("BPCustomerNumber", BPCustomerNumber);
            writer.WriteStringValue("ContactPerson", ContactPerson);
            writer.WriteStringValue("CustomerPartnerDescription", CustomerPartnerDescription);
            writer.WriteBoolValue("DefaultPartner", DefaultPartner);
            writer.WriteStringValue("PersonnelNumber", PersonnelNumber);
            writer.WriteStringValue("Supplier", Supplier);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
