// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace S4HANABusinessPartners.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class A_SupplierTypeCreate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Account Number of the Alternative Payee</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternativePayeeAccountNumber { get; set; }
#nullable restore
#else
        public string AlternativePayeeAccountNumber { get; set; }
#endif
        /// <summary>Authorization Group</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthorizationGroup { get; set; }
#nullable restore
#else
        public string AuthorizationGroup { get; set; }
#endif
        /// <summary>Date of Birth of the Person Subject to Withholding Tax</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BirthDate { get; set; }
#nullable restore
#else
        public string BirthDate { get; set; }
#endif
        /// <summary>Tax Split</summary>
        public bool? BRTaxIsSplit { get; set; }
        /// <summary>Customer Number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Customer { get; set; }
#nullable restore
#else
        public string Customer { get; set; }
#endif
        /// <summary>Instruction Key for Data Medium Exchange</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DataExchangeInstructionKey { get; set; }
#nullable restore
#else
        public string DataExchangeInstructionKey { get; set; }
#endif
        /// <summary>Central Deletion Flag for Master Record</summary>
        public bool? DeletionIndicator { get; set; }
        /// <summary>Account number of the master record with fiscal address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FiscalAddress { get; set; }
#nullable restore
#else
        public string FiscalAddress { get; set; }
#endif
        /// <summary>Payment Block</summary>
        public bool? PaymentIsBlockedForSupplier { get; set; }
        /// <summary>The PaymentReason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentReason { get; set; }
#nullable restore
#else
        public string PaymentReason { get; set; }
#endif
        /// <summary>Central posting block</summary>
        public bool? PostingIsBlocked { get; set; }
        /// <summary>Centrally imposed purchasing block</summary>
        public bool? PurchasingIsBlocked { get; set; }
        /// <summary>The ResponsibleType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResponsibleType { get; set; }
#nullable restore
#else
        public string ResponsibleType { get; set; }
#endif
        /// <summary>Supplier indicator relevant for proof of delivery</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SuplrProofOfDelivRlvtCode { get; set; }
#nullable restore
#else
        public string SuplrProofOfDelivRlvtCode { get; set; }
#endif
        /// <summary>Validity Date of Certification</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SuplrQltyInProcmtCertfnValidTo { get; set; }
#nullable restore
#else
        public string SuplrQltyInProcmtCertfnValidTo { get; set; }
#endif
        /// <summary>Supplier&apos;s QM System</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SuplrQualityManagementSystem { get; set; }
#nullable restore
#else
        public string SuplrQualityManagementSystem { get; set; }
#endif
        /// <summary>Account Number of Supplier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Supplier { get; set; }
#nullable restore
#else
        public string Supplier { get; set; }
#endif
        /// <summary>Vendor account group</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SupplierAccountGroup { get; set; }
#nullable restore
#else
        public string SupplierAccountGroup { get; set; }
#endif
        /// <summary>The SupplierCorporateGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SupplierCorporateGroup { get; set; }
#nullable restore
#else
        public string SupplierCorporateGroup { get; set; }
#endif
        /// <summary>Function That Will Be Blocked</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SupplierProcurementBlock { get; set; }
#nullable restore
#else
        public string SupplierProcurementBlock { get; set; }
#endif
        /// <summary>Tax Number at Responsible Tax Authority</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaxNumberResponsible { get; set; }
#nullable restore
#else
        public string TaxNumberResponsible { get; set; }
#endif
        /// <summary>Tax Number Type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaxNumberType { get; set; }
#nullable restore
#else
        public string TaxNumberType { get; set; }
#endif
        /// <summary>The to_SupplierCompany property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate_to_SupplierCompany? ToSupplierCompany { get; set; }
#nullable restore
#else
        public global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate_to_SupplierCompany ToSupplierCompany { get; set; }
#endif
        /// <summary>The to_SupplierPurchasingOrg property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate_to_SupplierPurchasingOrg? ToSupplierPurchasingOrg { get; set; }
#nullable restore
#else
        public global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate_to_SupplierPurchasingOrg ToSupplierPurchasingOrg { get; set; }
#endif
        /// <summary>The to_SupplierText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate_to_SupplierText? ToSupplierText { get; set; }
#nullable restore
#else
        public global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate_to_SupplierText ToSupplierText { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate"/> and sets the default values.
        /// </summary>
        public A_SupplierTypeCreate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AlternativePayeeAccountNumber", n => { AlternativePayeeAccountNumber = n.GetStringValue(); } },
                { "AuthorizationGroup", n => { AuthorizationGroup = n.GetStringValue(); } },
                { "BR_TaxIsSplit", n => { BRTaxIsSplit = n.GetBoolValue(); } },
                { "BirthDate", n => { BirthDate = n.GetStringValue(); } },
                { "Customer", n => { Customer = n.GetStringValue(); } },
                { "DataExchangeInstructionKey", n => { DataExchangeInstructionKey = n.GetStringValue(); } },
                { "DeletionIndicator", n => { DeletionIndicator = n.GetBoolValue(); } },
                { "FiscalAddress", n => { FiscalAddress = n.GetStringValue(); } },
                { "PaymentIsBlockedForSupplier", n => { PaymentIsBlockedForSupplier = n.GetBoolValue(); } },
                { "PaymentReason", n => { PaymentReason = n.GetStringValue(); } },
                { "PostingIsBlocked", n => { PostingIsBlocked = n.GetBoolValue(); } },
                { "PurchasingIsBlocked", n => { PurchasingIsBlocked = n.GetBoolValue(); } },
                { "ResponsibleType", n => { ResponsibleType = n.GetStringValue(); } },
                { "SuplrProofOfDelivRlvtCode", n => { SuplrProofOfDelivRlvtCode = n.GetStringValue(); } },
                { "SuplrQltyInProcmtCertfnValidTo", n => { SuplrQltyInProcmtCertfnValidTo = n.GetStringValue(); } },
                { "SuplrQualityManagementSystem", n => { SuplrQualityManagementSystem = n.GetStringValue(); } },
                { "Supplier", n => { Supplier = n.GetStringValue(); } },
                { "SupplierAccountGroup", n => { SupplierAccountGroup = n.GetStringValue(); } },
                { "SupplierCorporateGroup", n => { SupplierCorporateGroup = n.GetStringValue(); } },
                { "SupplierProcurementBlock", n => { SupplierProcurementBlock = n.GetStringValue(); } },
                { "TaxNumberResponsible", n => { TaxNumberResponsible = n.GetStringValue(); } },
                { "TaxNumberType", n => { TaxNumberType = n.GetStringValue(); } },
                { "to_SupplierCompany", n => { ToSupplierCompany = n.GetObjectValue<global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate_to_SupplierCompany>(global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate_to_SupplierCompany.CreateFromDiscriminatorValue); } },
                { "to_SupplierPurchasingOrg", n => { ToSupplierPurchasingOrg = n.GetObjectValue<global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate_to_SupplierPurchasingOrg>(global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate_to_SupplierPurchasingOrg.CreateFromDiscriminatorValue); } },
                { "to_SupplierText", n => { ToSupplierText = n.GetObjectValue<global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate_to_SupplierText>(global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate_to_SupplierText.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AlternativePayeeAccountNumber", AlternativePayeeAccountNumber);
            writer.WriteStringValue("AuthorizationGroup", AuthorizationGroup);
            writer.WriteStringValue("BirthDate", BirthDate);
            writer.WriteBoolValue("BR_TaxIsSplit", BRTaxIsSplit);
            writer.WriteStringValue("Customer", Customer);
            writer.WriteStringValue("DataExchangeInstructionKey", DataExchangeInstructionKey);
            writer.WriteBoolValue("DeletionIndicator", DeletionIndicator);
            writer.WriteStringValue("FiscalAddress", FiscalAddress);
            writer.WriteBoolValue("PaymentIsBlockedForSupplier", PaymentIsBlockedForSupplier);
            writer.WriteStringValue("PaymentReason", PaymentReason);
            writer.WriteBoolValue("PostingIsBlocked", PostingIsBlocked);
            writer.WriteBoolValue("PurchasingIsBlocked", PurchasingIsBlocked);
            writer.WriteStringValue("ResponsibleType", ResponsibleType);
            writer.WriteStringValue("SuplrProofOfDelivRlvtCode", SuplrProofOfDelivRlvtCode);
            writer.WriteStringValue("SuplrQltyInProcmtCertfnValidTo", SuplrQltyInProcmtCertfnValidTo);
            writer.WriteStringValue("SuplrQualityManagementSystem", SuplrQualityManagementSystem);
            writer.WriteStringValue("Supplier", Supplier);
            writer.WriteStringValue("SupplierAccountGroup", SupplierAccountGroup);
            writer.WriteStringValue("SupplierCorporateGroup", SupplierCorporateGroup);
            writer.WriteStringValue("SupplierProcurementBlock", SupplierProcurementBlock);
            writer.WriteStringValue("TaxNumberResponsible", TaxNumberResponsible);
            writer.WriteStringValue("TaxNumberType", TaxNumberType);
            writer.WriteObjectValue<global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate_to_SupplierCompany>("to_SupplierCompany", ToSupplierCompany);
            writer.WriteObjectValue<global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate_to_SupplierPurchasingOrg>("to_SupplierPurchasingOrg", ToSupplierPurchasingOrg);
            writer.WriteObjectValue<global::S4HANABusinessPartners.Client.Models.A_SupplierTypeCreate_to_SupplierText>("to_SupplierText", ToSupplierText);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
