// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace S4HANABusinessPartners.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DuplicateCheckResult : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The BusinessPartner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessPartner { get; set; }
#nullable restore
#else
        public string BusinessPartner { get; set; }
#endif
        /// <summary>The BusinessPartnerFullName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessPartnerFullName { get; set; }
#nullable restore
#else
        public string BusinessPartnerFullName { get; set; }
#endif
        /// <summary>The City property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? City { get; set; }
#nullable restore
#else
        public string City { get; set; }
#endif
        /// <summary>The Country property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Country { get; set; }
#nullable restore
#else
        public string Country { get; set; }
#endif
        /// <summary>The CountryName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryName { get; set; }
#nullable restore
#else
        public string CountryName { get; set; }
#endif
        /// <summary>The HouseNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HouseNumber { get; set; }
#nullable restore
#else
        public string HouseNumber { get; set; }
#endif
        /// <summary>The MatchRuleName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MatchRuleName { get; set; }
#nullable restore
#else
        public string MatchRuleName { get; set; }
#endif
        /// <summary>The MatchScore property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MatchScore { get; set; }
#nullable restore
#else
        public string MatchScore { get; set; }
#endif
        /// <summary>The PostalCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostalCode { get; set; }
#nullable restore
#else
        public string PostalCode { get; set; }
#endif
        /// <summary>The Region property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Region { get; set; }
#nullable restore
#else
        public string Region { get; set; }
#endif
        /// <summary>The RegionName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RegionName { get; set; }
#nullable restore
#else
        public string RegionName { get; set; }
#endif
        /// <summary>The StreetName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StreetName { get; set; }
#nullable restore
#else
        public string StreetName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.Models.DuplicateCheckResult"/> and sets the default values.
        /// </summary>
        public DuplicateCheckResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.Models.DuplicateCheckResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::S4HANABusinessPartners.Client.Models.DuplicateCheckResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::S4HANABusinessPartners.Client.Models.DuplicateCheckResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "BusinessPartner", n => { BusinessPartner = n.GetStringValue(); } },
                { "BusinessPartnerFullName", n => { BusinessPartnerFullName = n.GetStringValue(); } },
                { "City", n => { City = n.GetStringValue(); } },
                { "Country", n => { Country = n.GetStringValue(); } },
                { "CountryName", n => { CountryName = n.GetStringValue(); } },
                { "HouseNumber", n => { HouseNumber = n.GetStringValue(); } },
                { "MatchRuleName", n => { MatchRuleName = n.GetStringValue(); } },
                { "MatchScore", n => { MatchScore = n.GetStringValue(); } },
                { "PostalCode", n => { PostalCode = n.GetStringValue(); } },
                { "Region", n => { Region = n.GetStringValue(); } },
                { "RegionName", n => { RegionName = n.GetStringValue(); } },
                { "StreetName", n => { StreetName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("BusinessPartner", BusinessPartner);
            writer.WriteStringValue("BusinessPartnerFullName", BusinessPartnerFullName);
            writer.WriteStringValue("City", City);
            writer.WriteStringValue("Country", Country);
            writer.WriteStringValue("CountryName", CountryName);
            writer.WriteStringValue("HouseNumber", HouseNumber);
            writer.WriteStringValue("MatchRuleName", MatchRuleName);
            writer.WriteStringValue("MatchScore", MatchScore);
            writer.WriteStringValue("PostalCode", PostalCode);
            writer.WriteStringValue("Region", Region);
            writer.WriteStringValue("RegionName", RegionName);
            writer.WriteStringValue("StreetName", StreetName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
