// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using S4HANABusinessPartners.Client.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberPatchRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The d property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::S4HANABusinessPartners.Client.Models.A_AddressPhoneNumberTypeUpdate? D { get; set; }
#nullable restore
#else
        public global::S4HANABusinessPartners.Client.Models.A_AddressPhoneNumberTypeUpdate D { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberPatchRequestBody"/> and sets the default values.
        /// </summary>
        public A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberPatchRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberPatchRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberPatchRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberPatchRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "d", n => { D = n.GetObjectValue<global::S4HANABusinessPartners.Client.Models.A_AddressPhoneNumberTypeUpdate>(global::S4HANABusinessPartners.Client.Models.A_AddressPhoneNumberTypeUpdate.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::S4HANABusinessPartners.Client.Models.A_AddressPhoneNumberTypeUpdate>("d", D);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
