// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using S4HANABusinessPartners.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber
{
    /// <summary>
    /// Builds and executes requests for operations under \A_AddressPhoneNumber(AddressID=&apos;{AddressID}&apos;,Person=&apos;{Person}&apos;,OrdinalNumber=&apos;{OrdinalNumber}&apos;)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="addressID">Address Number</param>
        /// <param name="ordinalNumber">Sequence Number</param>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="person">Person Number</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter, string addressID = "", string ordinalNumber = "", string person = "") : base(requestAdapter, "{+baseurl}/A_AddressPhoneNumber(AddressID='{AddressID}',Person='{Person}',OrdinalNumber='{OrdinalNumber}'){?%24select}", pathParameters)
        {
            if (!string.IsNullOrWhiteSpace(addressID)) PathParameters.Add("AddressID", addressID);
            if (!string.IsNullOrWhiteSpace(ordinalNumber)) PathParameters.Add("OrdinalNumber", ordinalNumber);
            if (!string.IsNullOrWhiteSpace(person)) PathParameters.Add("Person", person);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/A_AddressPhoneNumber(AddressID='{AddressID}',Person='{Person}',OrdinalNumber='{OrdinalNumber}'){?%24select}", rawUrl)
        {
        }
        /// <summary>
        /// Delete business partner mobile/telephone address data of the record identified by AddressID, Person, and OrdinalNumber fields.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retreives mobile/telephone address record by AddressID, Person and OrdinalNumber.
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberGetResponse?> GetAsA_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberGetResponseAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilder.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberGetResponse> GetAsA_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberGetResponseAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilder.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberGetResponse>(requestInfo, global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retreives mobile/telephone address record by AddressID, Person and OrdinalNumber.
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
        [Obsolete("This method is obsolete. Use GetAsA_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberResponse?> GetAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilder.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberResponse> GetAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilder.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberResponse>(requestInfo, global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates business partner mobile/telephone address data of the record identified by AddressID, Person, and OrdinalNumber.
        /// </summary>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PatchAsync(global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PatchAsync(global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete business partner mobile/telephone address data of the record identified by AddressID, Person, and OrdinalNumber fields.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retreives mobile/telephone address record by AddressID, Person and OrdinalNumber.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilder.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilder.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates business partner mobile/telephone address data of the record identified by AddressID, Person, and OrdinalNumber.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilder WithUrl(string rawUrl)
        {
            return new global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Retreives mobile/telephone address record by AddressID, Person and OrdinalNumber.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilderGetQueryParameters 
        {
            /// <summary>Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=68)</summary>
            [Obsolete("This property is deprecated, use SelectAsGetSelectQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24select")]
            public string[]? Select { get; set; }
#nullable restore
#else
            [QueryParameter("%24select")]
            public string[] Select { get; set; }
#endif
            /// <summary>Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=68)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24select")]
            public global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.GetSelectQueryParameterType[]? SelectAsGetSelectQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("%24select")]
            public global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.GetSelectQueryParameterType[] SelectAsGetSelectQueryParameterType { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilderGetRequestConfiguration : RequestConfiguration<global::S4HANABusinessPartners.Client.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumber.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilder.A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_AddressPhoneNumberWithAddressIDWithPersonWithOrdinalNumberRequestBuilderPatchRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
