// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace S4HANABusinessPartners.Client.A_BPContactToAddressWithRelationshipNumberWithBusinessPartnerCompanyWithBusinessPartnerPersonValidityEndDateDatetimeWithValidityEndDateWithAddressID.To_BPRelshpCntctPersnEmailAddr
{
    [Obsolete("This class is obsolete. Use To_BPRelshpCntctPersnEmailAddrGetResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class To_BPRelshpCntctPersnEmailAddrResponse : global::S4HANABusinessPartners.Client.A_BPContactToAddressWithRelationshipNumberWithBusinessPartnerCompanyWithBusinessPartnerPersonValidityEndDateDatetimeWithValidityEndDateWithAddressID.To_BPRelshpCntctPersnEmailAddr.To_BPRelshpCntctPersnEmailAddrGetResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_BPContactToAddressWithRelationshipNumberWithBusinessPartnerCompanyWithBusinessPartnerPersonValidityEndDateDatetimeWithValidityEndDateWithAddressID.To_BPRelshpCntctPersnEmailAddr.To_BPRelshpCntctPersnEmailAddrResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::S4HANABusinessPartners.Client.A_BPContactToAddressWithRelationshipNumberWithBusinessPartnerCompanyWithBusinessPartnerPersonValidityEndDateDatetimeWithValidityEndDateWithAddressID.To_BPRelshpCntctPersnEmailAddr.To_BPRelshpCntctPersnEmailAddrResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::S4HANABusinessPartners.Client.A_BPContactToAddressWithRelationshipNumberWithBusinessPartnerCompanyWithBusinessPartnerPersonValidityEndDateDatetimeWithValidityEndDateWithAddressID.To_BPRelshpCntctPersnEmailAddr.To_BPRelshpCntctPersnEmailAddrResponse();
        }
    }
}
#pragma warning restore CS0618
