// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_BusinessPartnerWithBusinessPartner.To_BPFiscalYearInformation
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrderbyQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BusinessPartner")]
        #pragma warning disable CS1591
        BusinessPartner,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartner desc")]
        #pragma warning disable CS1591
        BusinessPartnerDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerFiscalYear")]
        #pragma warning disable CS1591
        BusinessPartnerFiscalYear,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartnerFiscalYear desc")]
        #pragma warning disable CS1591
        BusinessPartnerFiscalYearDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPBalanceSheetCurrency")]
        #pragma warning disable CS1591
        BPBalanceSheetCurrency,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPBalanceSheetCurrency desc")]
        #pragma warning disable CS1591
        BPBalanceSheetCurrencyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPAnnualStockholderMeetingDate")]
        #pragma warning disable CS1591
        BPAnnualStockholderMeetingDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPAnnualStockholderMeetingDate desc")]
        #pragma warning disable CS1591
        BPAnnualStockholderMeetingDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPFiscalYearStartDate")]
        #pragma warning disable CS1591
        BPFiscalYearStartDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPFiscalYearStartDate desc")]
        #pragma warning disable CS1591
        BPFiscalYearStartDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPFiscalYearEndDate")]
        #pragma warning disable CS1591
        BPFiscalYearEndDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPFiscalYearEndDate desc")]
        #pragma warning disable CS1591
        BPFiscalYearEndDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPFiscalYearIsClosed")]
        #pragma warning disable CS1591
        BPFiscalYearIsClosed,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPFiscalYearIsClosed desc")]
        #pragma warning disable CS1591
        BPFiscalYearIsClosedDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPFiscalYearClosingDate")]
        #pragma warning disable CS1591
        BPFiscalYearClosingDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPFiscalYearClosingDate desc")]
        #pragma warning disable CS1591
        BPFiscalYearClosingDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPFsclYrCnsldtdFinStatementDte")]
        #pragma warning disable CS1591
        BPFsclYrCnsldtdFinStatementDte,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPFsclYrCnsldtdFinStatementDte desc")]
        #pragma warning disable CS1591
        BPFsclYrCnsldtdFinStatementDteDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPCapitalStockAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPCapitalStockAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPCapitalStockAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPCapitalStockAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPIssdStockCptlAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPIssdStockCptlAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPIssdStockCptlAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPIssdStockCptlAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPPartcipnCertAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPPartcipnCertAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPPartcipnCertAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPPartcipnCertAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPEquityCapitalAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPEquityCapitalAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPEquityCapitalAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPEquityCapitalAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPGrossPremiumAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPGrossPremiumAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPGrossPremiumAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPGrossPremiumAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPNetPremiumAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPNetPremiumAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPNetPremiumAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPNetPremiumAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPAnnualSalesAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPAnnualSalesAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPAnnualSalesAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPAnnualSalesAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPAnnualNetIncAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPAnnualNetIncAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPAnnualNetIncAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPAnnualNetIncAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPDividendDistrAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPDividendDistrAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPDividendDistrAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPDividendDistrAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPDebtRatioInYears")]
        #pragma warning disable CS1591
        BPDebtRatioInYears,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPDebtRatioInYears desc")]
        #pragma warning disable CS1591
        BPDebtRatioInYearsDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPAnnualPnLAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPAnnualPnLAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPAnnualPnLAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPAnnualPnLAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPBalSheetTotalAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPBalSheetTotalAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPBalSheetTotalAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPBalSheetTotalAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPNumberOfEmployees")]
        #pragma warning disable CS1591
        BPNumberOfEmployees,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPNumberOfEmployees desc")]
        #pragma warning disable CS1591
        BPNumberOfEmployeesDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPCptlReserveAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPCptlReserveAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPCptlReserveAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPCptlReserveAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPLglRevnRsrvAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPLglRevnRsrvAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPLglRevnRsrvAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPLglRevnRsrvAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "RevnRsrvOwnStkAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        RevnRsrvOwnStkAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "RevnRsrvOwnStkAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        RevnRsrvOwnStkAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPStatryReserveAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPStatryReserveAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPStatryReserveAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPStatryReserveAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPOthRevnRsrvAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPOthRevnRsrvAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPOthRevnRsrvAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPOthRevnRsrvAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPPnLCarryfwdAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPPnLCarryfwdAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPPnLCarryfwdAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPPnLCarryfwdAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPSuborddLbltyAmtInBalShtCrcy")]
        #pragma warning disable CS1591
        BPSuborddLbltyAmtInBalShtCrcy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPSuborddLbltyAmtInBalShtCrcy desc")]
        #pragma warning disable CS1591
        BPSuborddLbltyAmtInBalShtCrcyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPRetOnTotalCptlEmpldInPercent")]
        #pragma warning disable CS1591
        BPRetOnTotalCptlEmpldInPercent,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPRetOnTotalCptlEmpldInPercent desc")]
        #pragma warning disable CS1591
        BPRetOnTotalCptlEmpldInPercentDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPDebtClearancePeriodInYears")]
        #pragma warning disable CS1591
        BPDebtClearancePeriodInYears,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPDebtClearancePeriodInYears desc")]
        #pragma warning disable CS1591
        BPDebtClearancePeriodInYearsDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPFinancingCoeffInPercent")]
        #pragma warning disable CS1591
        BPFinancingCoeffInPercent,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPFinancingCoeffInPercent desc")]
        #pragma warning disable CS1591
        BPFinancingCoeffInPercentDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPEquityRatioInPercent")]
        #pragma warning disable CS1591
        BPEquityRatioInPercent,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPEquityRatioInPercent desc")]
        #pragma warning disable CS1591
        BPEquityRatioInPercentDesc,
        #pragma warning restore CS1591
    }
}
