// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_BPRelationship
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrderbyQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "RelationshipNumber")]
        #pragma warning disable CS1591
        RelationshipNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "RelationshipNumber desc")]
        #pragma warning disable CS1591
        RelationshipNumberDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartner1")]
        #pragma warning disable CS1591
        BusinessPartner1,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartner1 desc")]
        #pragma warning disable CS1591
        BusinessPartner1Desc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartner2")]
        #pragma warning disable CS1591
        BusinessPartner2,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartner2 desc")]
        #pragma warning disable CS1591
        BusinessPartner2Desc,
        #pragma warning restore CS1591
        [EnumMember(Value = "ValidityEndDate")]
        #pragma warning disable CS1591
        ValidityEndDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "ValidityEndDate desc")]
        #pragma warning disable CS1591
        ValidityEndDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "ValidityStartDate")]
        #pragma warning disable CS1591
        ValidityStartDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "ValidityStartDate desc")]
        #pragma warning disable CS1591
        ValidityStartDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "IsStandardRelationship")]
        #pragma warning disable CS1591
        IsStandardRelationship,
        #pragma warning restore CS1591
        [EnumMember(Value = "IsStandardRelationship desc")]
        #pragma warning disable CS1591
        IsStandardRelationshipDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "RelationshipCategory")]
        #pragma warning disable CS1591
        RelationshipCategory,
        #pragma warning restore CS1591
        [EnumMember(Value = "RelationshipCategory desc")]
        #pragma warning disable CS1591
        RelationshipCategoryDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPRelationshipType")]
        #pragma warning disable CS1591
        BPRelationshipType,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPRelationshipType desc")]
        #pragma warning disable CS1591
        BPRelationshipTypeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CreatedByUser")]
        #pragma warning disable CS1591
        CreatedByUser,
        #pragma warning restore CS1591
        [EnumMember(Value = "CreatedByUser desc")]
        #pragma warning disable CS1591
        CreatedByUserDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CreationDate")]
        #pragma warning disable CS1591
        CreationDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "CreationDate desc")]
        #pragma warning disable CS1591
        CreationDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CreationTime")]
        #pragma warning disable CS1591
        CreationTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "CreationTime desc")]
        #pragma warning disable CS1591
        CreationTimeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "LastChangedByUser")]
        #pragma warning disable CS1591
        LastChangedByUser,
        #pragma warning restore CS1591
        [EnumMember(Value = "LastChangedByUser desc")]
        #pragma warning disable CS1591
        LastChangedByUserDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "LastChangeDate")]
        #pragma warning disable CS1591
        LastChangeDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "LastChangeDate desc")]
        #pragma warning disable CS1591
        LastChangeDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "LastChangeTime")]
        #pragma warning disable CS1591
        LastChangeTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "LastChangeTime desc")]
        #pragma warning disable CS1591
        LastChangeTimeDesc,
        #pragma warning restore CS1591
    }
}
