// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_CustSlsAreaAddrDepdntInfoWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithAddressID
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSelectQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Customer")]
        #pragma warning disable CS1591
        Customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "SalesOrganization")]
        #pragma warning disable CS1591
        SalesOrganization,
        #pragma warning restore CS1591
        [EnumMember(Value = "DistributionChannel")]
        #pragma warning disable CS1591
        DistributionChannel,
        #pragma warning restore CS1591
        [EnumMember(Value = "Division")]
        #pragma warning disable CS1591
        Division,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressID")]
        #pragma warning disable CS1591
        AddressID,
        #pragma warning restore CS1591
        [EnumMember(Value = "IncotermsClassification")]
        #pragma warning disable CS1591
        IncotermsClassification,
        #pragma warning restore CS1591
        [EnumMember(Value = "IncotermsLocation1")]
        #pragma warning disable CS1591
        IncotermsLocation1,
        #pragma warning restore CS1591
        [EnumMember(Value = "IncotermsLocation2")]
        #pragma warning disable CS1591
        IncotermsLocation2,
        #pragma warning restore CS1591
        [EnumMember(Value = "IncotermsSupChnLoc1AddlUUID")]
        #pragma warning disable CS1591
        IncotermsSupChnLoc1AddlUUID,
        #pragma warning restore CS1591
        [EnumMember(Value = "IncotermsSupChnLoc2AddlUUID")]
        #pragma warning disable CS1591
        IncotermsSupChnLoc2AddlUUID,
        #pragma warning restore CS1591
        [EnumMember(Value = "IncotermsSupChnDvtgLocAddlUUID")]
        #pragma warning disable CS1591
        IncotermsSupChnDvtgLocAddlUUID,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeliveryIsBlocked")]
        #pragma warning disable CS1591
        DeliveryIsBlocked,
        #pragma warning restore CS1591
        [EnumMember(Value = "SalesOffice")]
        #pragma warning disable CS1591
        SalesOffice,
        #pragma warning restore CS1591
        [EnumMember(Value = "SalesGroup")]
        #pragma warning disable CS1591
        SalesGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "ShippingCondition")]
        #pragma warning disable CS1591
        ShippingCondition,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupplyingPlant")]
        #pragma warning disable CS1591
        SupplyingPlant,
        #pragma warning restore CS1591
        [EnumMember(Value = "IncotermsVersion")]
        #pragma warning disable CS1591
        IncotermsVersion,
        #pragma warning restore CS1591
    }
}
