// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_CustomerTaxGrouping
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrderbyQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Customer")]
        #pragma warning disable CS1591
        Customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "Customer desc")]
        #pragma warning disable CS1591
        CustomerDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerTaxGroupingCode")]
        #pragma warning disable CS1591
        CustomerTaxGroupingCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerTaxGroupingCode desc")]
        #pragma warning disable CS1591
        CustomerTaxGroupingCodeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustTaxGrpExemptionCertificate")]
        #pragma warning disable CS1591
        CustTaxGrpExemptionCertificate,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustTaxGrpExemptionCertificate desc")]
        #pragma warning disable CS1591
        CustTaxGrpExemptionCertificateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustTaxGroupExemptionRate")]
        #pragma warning disable CS1591
        CustTaxGroupExemptionRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustTaxGroupExemptionRate desc")]
        #pragma warning disable CS1591
        CustTaxGroupExemptionRateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustTaxGroupExemptionStartDate")]
        #pragma warning disable CS1591
        CustTaxGroupExemptionStartDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustTaxGroupExemptionStartDate desc")]
        #pragma warning disable CS1591
        CustTaxGroupExemptionStartDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustTaxGroupExemptionEndDate")]
        #pragma warning disable CS1591
        CustTaxGroupExemptionEndDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustTaxGroupExemptionEndDate desc")]
        #pragma warning disable CS1591
        CustTaxGroupExemptionEndDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustTaxGroupSubjectedStartDate")]
        #pragma warning disable CS1591
        CustTaxGroupSubjectedStartDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustTaxGroupSubjectedStartDate desc")]
        #pragma warning disable CS1591
        CustTaxGroupSubjectedStartDateDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustTaxGroupSubjectedEndDate")]
        #pragma warning disable CS1591
        CustTaxGroupSubjectedEndDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustTaxGroupSubjectedEndDate desc")]
        #pragma warning disable CS1591
        CustTaxGroupSubjectedEndDateDesc,
        #pragma warning restore CS1591
    }
}
