// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_CustomerSalesAreaWithCustomerWithSalesOrganizationWithDistributionChannelWithDivision.To_SalesAreaText
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSelectQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Customer")]
        #pragma warning disable CS1591
        Customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "SalesOrganization")]
        #pragma warning disable CS1591
        SalesOrganization,
        #pragma warning restore CS1591
        [EnumMember(Value = "DistributionChannel")]
        #pragma warning disable CS1591
        DistributionChannel,
        #pragma warning restore CS1591
        [EnumMember(Value = "Division")]
        #pragma warning disable CS1591
        Division,
        #pragma warning restore CS1591
        [EnumMember(Value = "Language")]
        #pragma warning disable CS1591
        Language,
        #pragma warning restore CS1591
        [EnumMember(Value = "LongTextID")]
        #pragma warning disable CS1591
        LongTextID,
        #pragma warning restore CS1591
        [EnumMember(Value = "LongText")]
        #pragma warning disable CS1591
        LongText,
        #pragma warning restore CS1591
    }
}
