// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_AddressFaxNumber
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSelectQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "AddressID")]
        #pragma warning disable CS1591
        AddressID,
        #pragma warning restore CS1591
        [EnumMember(Value = "Person")]
        #pragma warning disable CS1591
        Person,
        #pragma warning restore CS1591
        [EnumMember(Value = "OrdinalNumber")]
        #pragma warning disable CS1591
        OrdinalNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "IsDefaultFaxNumber")]
        #pragma warning disable CS1591
        IsDefaultFaxNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "FaxCountry")]
        #pragma warning disable CS1591
        FaxCountry,
        #pragma warning restore CS1591
        [EnumMember(Value = "FaxNumber")]
        #pragma warning disable CS1591
        FaxNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "FaxNumberExtension")]
        #pragma warning disable CS1591
        FaxNumberExtension,
        #pragma warning restore CS1591
        [EnumMember(Value = "InternationalFaxNumber")]
        #pragma warning disable CS1591
        InternationalFaxNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressCommunicationRemarkText")]
        #pragma warning disable CS1591
        AddressCommunicationRemarkText,
        #pragma warning restore CS1591
    }
}
