// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_CustSlsAreaAddrDepdntTaxInfoWithCustomerWithSalesOrganizationWithDistributionChannelWithDivisionWithAddressIDWithDepartureCountryWithCustomerTaxCategory
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSelectQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Customer")]
        #pragma warning disable CS1591
        Customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "SalesOrganization")]
        #pragma warning disable CS1591
        SalesOrganization,
        #pragma warning restore CS1591
        [EnumMember(Value = "DistributionChannel")]
        #pragma warning disable CS1591
        DistributionChannel,
        #pragma warning restore CS1591
        [EnumMember(Value = "Division")]
        #pragma warning disable CS1591
        Division,
        #pragma warning restore CS1591
        [EnumMember(Value = "AddressID")]
        #pragma warning disable CS1591
        AddressID,
        #pragma warning restore CS1591
        [EnumMember(Value = "DepartureCountry")]
        #pragma warning disable CS1591
        DepartureCountry,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerTaxCategory")]
        #pragma warning disable CS1591
        CustomerTaxCategory,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerTaxClassification")]
        #pragma warning disable CS1591
        CustomerTaxClassification,
        #pragma warning restore CS1591
    }
}
