// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using S4HANABusinessPartners.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter
{
    /// <summary>
    /// Builds and executes requests for operations under \A_SupplierPartnerFunc(Supplier=&apos;{Supplier}&apos;,PurchasingOrganization=&apos;{PurchasingOrganization}&apos;,SupplierSubrange=&apos;{SupplierSubrange}&apos;,Plant=&apos;{Plant}&apos;,PartnerFunction=&apos;{PartnerFunction}&apos;,PartnerCounter=&apos;{PartnerCounter}&apos;)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="partnerCounter">Partner counter</param>
        /// <param name="partnerFunction">Partner Function</param>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="plant">Plant</param>
        /// <param name="purchasingOrganization">Purchasing Organization</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        /// <param name="supplier">Account Number of Supplier</param>
        /// <param name="supplierSubrange">Supplier Subrange</param>
        public A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter, string partnerCounter = "", string partnerFunction = "", string plant = "", string purchasingOrganization = "", string supplier = "", string supplierSubrange = "") : base(requestAdapter, "{+baseurl}/A_SupplierPartnerFunc(Supplier='{Supplier}',PurchasingOrganization='{PurchasingOrganization}',SupplierSubrange='{SupplierSubrange}',Plant='{Plant}',PartnerFunction='{PartnerFunction}',PartnerCounter='{PartnerCounter}'){?%24select}", pathParameters)
        {
            if (!string.IsNullOrWhiteSpace(partnerCounter)) PathParameters.Add("PartnerCounter", partnerCounter);
            if (!string.IsNullOrWhiteSpace(partnerFunction)) PathParameters.Add("PartnerFunction", partnerFunction);
            if (!string.IsNullOrWhiteSpace(plant)) PathParameters.Add("Plant", plant);
            if (!string.IsNullOrWhiteSpace(purchasingOrganization)) PathParameters.Add("PurchasingOrganization", purchasingOrganization);
            if (!string.IsNullOrWhiteSpace(supplier)) PathParameters.Add("Supplier", supplier);
            if (!string.IsNullOrWhiteSpace(supplierSubrange)) PathParameters.Add("SupplierSubrange", supplierSubrange);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/A_SupplierPartnerFunc(Supplier='{Supplier}',PurchasingOrganization='{PurchasingOrganization}',SupplierSubrange='{SupplierSubrange}',Plant='{Plant}',PartnerFunction='{PartnerFunction}',PartnerCounter='{PartnerCounter}'){?%24select}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes partner function record by Supplier, PurchasingOrganization, SupplierSubrange, Plant, PartnerCounter and PartnerFunction
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves partner function data by Supplier, PurchasingOrganization, SupplierSubrange, Plant, PartnerCounter, and PartnerFunction.
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterGetResponse?> GetAsA_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterGetResponseAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilder.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterGetResponse> GetAsA_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterGetResponseAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilder.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterGetResponse>(requestInfo, global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves partner function data by Supplier, PurchasingOrganization, SupplierSubrange, Plant, PartnerCounter, and PartnerFunction.
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
        [Obsolete("This method is obsolete. Use GetAsA_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterResponse?> GetAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilder.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterResponse> GetAsync(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilder.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterResponse>(requestInfo, global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates partner function record by Supplier, PurchasingOrganization, SupplierSubrange, Plant, PartnerCounter, and PartnerFunction.
        /// </summary>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::S4HANABusinessPartners.Client.Models.Error">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PatchAsync(global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PatchAsync(global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::S4HANABusinessPartners.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes partner function record by Supplier, PurchasingOrganization, SupplierSubrange, Plant, PartnerCounter and PartnerFunction
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retrieves partner function data by Supplier, PurchasingOrganization, SupplierSubrange, Plant, PartnerCounter, and PartnerFunction.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilder.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilder.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates partner function record by Supplier, PurchasingOrganization, SupplierSubrange, Plant, PartnerCounter, and PartnerFunction.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilder WithUrl(string rawUrl)
        {
            return new global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Retrieves partner function data by Supplier, PurchasingOrganization, SupplierSubrange, Plant, PartnerCounter, and PartnerFunction.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilderGetQueryParameters 
        {
            /// <summary>Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=68)</summary>
            [Obsolete("This property is deprecated, use SelectAsGetSelectQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24select")]
            public string[]? Select { get; set; }
#nullable restore
#else
            [QueryParameter("%24select")]
            public string[] Select { get; set; }
#endif
            /// <summary>Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page=68)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24select")]
            public global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.GetSelectQueryParameterType[]? SelectAsGetSelectQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("%24select")]
            public global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.GetSelectQueryParameterType[] SelectAsGetSelectQueryParameterType { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilderGetRequestConfiguration : RequestConfiguration<global::S4HANABusinessPartners.Client.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounter.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilder.A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class A_SupplierPartnerFuncWithSupplierWithPurchasingOrganizationWithSupplierSubrangeWithPlantWithPartnerFunctionWithPartnerCounterRequestBuilderPatchRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
