// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_SupplierCompanyWithSupplierWithCompanyCode.To_Supplier
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetExpandQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "to_SupplierCompany")]
        #pragma warning disable CS1591
        To_SupplierCompany,
        #pragma warning restore CS1591
        [EnumMember(Value = "to_SupplierPurchasingOrg")]
        #pragma warning disable CS1591
        To_SupplierPurchasingOrg,
        #pragma warning restore CS1591
        [EnumMember(Value = "to_SupplierText")]
        #pragma warning disable CS1591
        To_SupplierText,
        #pragma warning restore CS1591
    }
}
