// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace S4HANABusinessPartners.Client.A_BusinessPartnerWithBusinessPartner.To_BPRelationship
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSelectQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "RelationshipNumber")]
        #pragma warning disable CS1591
        RelationshipNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartner1")]
        #pragma warning disable CS1591
        BusinessPartner1,
        #pragma warning restore CS1591
        [EnumMember(Value = "BusinessPartner2")]
        #pragma warning disable CS1591
        BusinessPartner2,
        #pragma warning restore CS1591
        [EnumMember(Value = "ValidityEndDate")]
        #pragma warning disable CS1591
        ValidityEndDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "ValidityStartDate")]
        #pragma warning disable CS1591
        ValidityStartDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "IsStandardRelationship")]
        #pragma warning disable CS1591
        IsStandardRelationship,
        #pragma warning restore CS1591
        [EnumMember(Value = "RelationshipCategory")]
        #pragma warning disable CS1591
        RelationshipCategory,
        #pragma warning restore CS1591
        [EnumMember(Value = "BPRelationshipType")]
        #pragma warning disable CS1591
        BPRelationshipType,
        #pragma warning restore CS1591
        [EnumMember(Value = "CreatedByUser")]
        #pragma warning disable CS1591
        CreatedByUser,
        #pragma warning restore CS1591
        [EnumMember(Value = "CreationDate")]
        #pragma warning disable CS1591
        CreationDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "CreationTime")]
        #pragma warning disable CS1591
        CreationTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "LastChangedByUser")]
        #pragma warning disable CS1591
        LastChangedByUser,
        #pragma warning restore CS1591
        [EnumMember(Value = "LastChangeDate")]
        #pragma warning disable CS1591
        LastChangeDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "LastChangeTime")]
        #pragma warning disable CS1591
        LastChangeTime,
        #pragma warning restore CS1591
    }
}
